package com.imopan.adv.platform.vo.fos;

import com.imopan.adv.platform.common.BaseBean;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FosChannelInfoV2 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.SIGN
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.FULL_NAME
     *
     * @mbggenerated
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.STATUS
     *
     * @mbggenerated
     */
    private int status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.CHANNEL_CATEGORY_ID
     *
     * @mbggenerated
     */
    private Byte channelCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.COMPANY_TEL
     *
     * @mbggenerated
     */
    private String companyTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.COMPANY_PROFILE
     *
     * @mbggenerated
     */
    private String companyProfile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.CHANNEL_INTERFACE_TYPE
     *
     * @mbggenerated
     */
    private Byte channelInterfaceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.CONTACT_NAME
     *
     * @mbggenerated
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.CONTACT_TEL
     *
     * @mbggenerated
     */
    private String contactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.MP_BUSINESS_ID
     *
     * @mbggenerated
     */
    private Integer mpBusinessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.MP_BUSINESS_NAME
     *
     * @mbggenerated
     */
    private String mpBusinessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info_v2.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table channel_info_v2
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.ID
     *
     * @return the value of channel_info_v2.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.ID
     *
     * @param id the value for channel_info_v2.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.SIGN
     *
     * @return the value of channel_info_v2.SIGN
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.SIGN
     *
     * @param sign the value for channel_info_v2.SIGN
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.NAME
     *
     * @return the value of channel_info_v2.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.NAME
     *
     * @param name the value for channel_info_v2.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.FULL_NAME
     *
     * @return the value of channel_info_v2.FULL_NAME
     *
     * @mbggenerated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.FULL_NAME
     *
     * @param fullName the value for channel_info_v2.FULL_NAME
     *
     * @mbggenerated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.STATUS
     *
     * @return the value of channel_info_v2.STATUS
     *
     * @mbggenerated
     */
    public int getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.STATUS
     *
     * @param status the value for channel_info_v2.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.CHANNEL_CATEGORY_ID
     *
     * @return the value of channel_info_v2.CHANNEL_CATEGORY_ID
     *
     * @mbggenerated
     */
    public Byte getChannelCategoryId() {
        return channelCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.CHANNEL_CATEGORY_ID
     *
     * @param channelCategoryId the value for channel_info_v2.CHANNEL_CATEGORY_ID
     *
     * @mbggenerated
     */
    public void setChannelCategoryId(Byte channelCategoryId) {
        this.channelCategoryId = channelCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.COMPANY_TEL
     *
     * @return the value of channel_info_v2.COMPANY_TEL
     *
     * @mbggenerated
     */
    public String getCompanyTel() {
        return companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.COMPANY_TEL
     *
     * @param companyTel the value for channel_info_v2.COMPANY_TEL
     *
     * @mbggenerated
     */
    public void setCompanyTel(String companyTel) {
        this.companyTel = companyTel == null ? null : companyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.COMPANY_PROFILE
     *
     * @return the value of channel_info_v2.COMPANY_PROFILE
     *
     * @mbggenerated
     */
    public String getCompanyProfile() {
        return companyProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.COMPANY_PROFILE
     *
     * @param companyProfile the value for channel_info_v2.COMPANY_PROFILE
     *
     * @mbggenerated
     */
    public void setCompanyProfile(String companyProfile) {
        this.companyProfile = companyProfile == null ? null : companyProfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.CHANNEL_INTERFACE_TYPE
     *
     * @return the value of channel_info_v2.CHANNEL_INTERFACE_TYPE
     *
     * @mbggenerated
     */
    public Byte getChannelInterfaceType() {
        return channelInterfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.CHANNEL_INTERFACE_TYPE
     *
     * @param channelInterfaceType the value for channel_info_v2.CHANNEL_INTERFACE_TYPE
     *
     * @mbggenerated
     */
    public void setChannelInterfaceType(Byte channelInterfaceType) {
        this.channelInterfaceType = channelInterfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.CONTACT_NAME
     *
     * @return the value of channel_info_v2.CONTACT_NAME
     *
     * @mbggenerated
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.CONTACT_NAME
     *
     * @param contactName the value for channel_info_v2.CONTACT_NAME
     *
     * @mbggenerated
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.CONTACT_TEL
     *
     * @return the value of channel_info_v2.CONTACT_TEL
     *
     * @mbggenerated
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.CONTACT_TEL
     *
     * @param contactTel the value for channel_info_v2.CONTACT_TEL
     *
     * @mbggenerated
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel == null ? null : contactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.MP_BUSINESS_ID
     *
     * @return the value of channel_info_v2.MP_BUSINESS_ID
     *
     * @mbggenerated
     */
    public Integer getMpBusinessId() {
        return mpBusinessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.MP_BUSINESS_ID
     *
     * @param mpBusinessId the value for channel_info_v2.MP_BUSINESS_ID
     *
     * @mbggenerated
     */
    public void setMpBusinessId(Integer mpBusinessId) {
        this.mpBusinessId = mpBusinessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.MP_BUSINESS_NAME
     *
     * @return the value of channel_info_v2.MP_BUSINESS_NAME
     *
     * @mbggenerated
     */
    public String getMpBusinessName() {
        return mpBusinessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.MP_BUSINESS_NAME
     *
     * @param mpBusinessName the value for channel_info_v2.MP_BUSINESS_NAME
     *
     * @mbggenerated
     */
    public void setMpBusinessName(String mpBusinessName) {
        this.mpBusinessName = mpBusinessName == null ? null : mpBusinessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.UPDATE_TIME
     *
     * @return the value of channel_info_v2.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.UPDATE_TIME
     *
     * @param updateTime the value for channel_info_v2.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info_v2.CREATE_TIME
     *
     * @return the value of channel_info_v2.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info_v2.CREATE_TIME
     *
     * @param createTime the value for channel_info_v2.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    
    private byte orderchannelStatus;
	private BigDecimal outerUnit;
	private byte autoFlag;
	

	public byte getAutoFlag() {
		return autoFlag;
	}

	public void setAutoFlag(byte autoFlag) {
		this.autoFlag = autoFlag;
	}

	public byte getOrderchannelStatus() {
		return orderchannelStatus;
	}

	public void setOrderchannelStatus(byte orderchannelStatus) {
		this.orderchannelStatus = orderchannelStatus;
	}

	public BigDecimal getOuterUnit() {
		return outerUnit;
	}

	public void setOuterUnit(BigDecimal outerUnit) {
		this.outerUnit = outerUnit;
	}
}