package com.imopan.adv.platform.vo.fos;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.imopan.adv.platform.common.VoBaseBean;
import com.imopan.adv.platform.exception.ImopanException;

public class FosReceiveOrderVo extends VoBaseBean implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.ID
	 * 
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.IDS
	 * 
	 * @mbggenerated
	 */
	private String ids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.CHANNEL_ID
	 * 
	 * @mbggenerated
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.CHANNEL_NAME
	 * 
	 * @mbggenerated
	 */
	private String channelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.CHANNEL_DIRECTOR_NAME
	 * 
	 * @mbggenerated
	 */
	private String channelDirectorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.C_UNIT
	 * 
	 * @mbggenerated
	 */
	private BigDecimal cUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.C_COUNT
	 * 
	 * @mbggenerated
	 */
	private Integer cCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.C_AMOUNT
	 * 
	 * @mbggenerated
	 */
	private BigDecimal cAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.SUB_AMOUNT
	 * 
	 * @mbggenerated
	 */
	private BigDecimal subAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.MEDIA_REBATE
	 * 
	 * @mbggenerated
	 */
	private BigDecimal mediaRebate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.OTHER_EXPENSE
	 * 
	 * @mbggenerated
	 */
	private BigDecimal otherExpense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.CHANNEL_CUT
	 * 
	 * @mbggenerated
	 */
	private BigDecimal channelCut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.CHANNEL_ORDER_NAME
	 * 
	 * @mbggenerated
	 */
	private String channelOrderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.COMPANY
	 * 
	 * @mbggenerated
	 */
	private String company;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.MONEY
	 * 
	 * @mbggenerated
	 */
	private BigDecimal money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.DATA_TIME
	 * 
	 * @mbggenerated
	 */
	private Date dataTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.TICKET_CODE
	 * 
	 * @mbggenerated
	 */
	private String ticketCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.TICKET_NUM
	 * 
	 * @mbggenerated
	 */
	private String ticketNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.TICKET_TIME
	 * 
	 * @mbggenerated
	 */
	private String ticketTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.STATUS
	 * 
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.PAY_MONEY
	 * 
	 * @mbggenerated
	 */
	private Long payMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.PAY_DATE
	 * 
	 * @mbggenerated
	 */
	private Date payDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.ADVANCE_PAY
	 * 
	 * @mbggenerated
	 */
	private BigDecimal advancePay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fos_receive_order.CHANNEL_ORDER_ID
	 * 
	 * @mbggenerated
	 */
	private Integer channelOrderId;
	private Date channelTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table fos_receive_order
	 * 
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.ID
	 * 
	 * @return the value of fos_receive_order.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.ID
	 * 
	 * @param id
	 *            the value for fos_receive_order.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.IDS
	 * 
	 * @return the value of fos_receive_order.IDS
	 * @mbggenerated
	 */
	public String getIds() {
		return ids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.IDS
	 * 
	 * @param ids
	 *            the value for fos_receive_order.IDS
	 * @mbggenerated
	 */
	public void setIds(String ids) {
		this.ids = ids == null ? null : ids.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.CHANNEL_ID
	 * 
	 * @return the value of fos_receive_order.CHANNEL_ID
	 * @mbggenerated
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.CHANNEL_ID
	 * 
	 * @param channelId
	 *            the value for fos_receive_order.CHANNEL_ID
	 * @mbggenerated
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.CHANNEL_NAME
	 * 
	 * @return the value of fos_receive_order.CHANNEL_NAME
	 * @mbggenerated
	 */
	public String getChannelName() {
		return channelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.CHANNEL_NAME
	 * 
	 * @param channelName
	 *            the value for fos_receive_order.CHANNEL_NAME
	 * @mbggenerated
	 */
	public void setChannelName(String channelName) {
		this.channelName = channelName == null ? null : channelName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.CHANNEL_DIRECTOR_NAME
	 * 
	 * @return the value of fos_receive_order.CHANNEL_DIRECTOR_NAME
	 * @mbggenerated
	 */
	public String getChannelDirectorName() {
		return channelDirectorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.CHANNEL_DIRECTOR_NAME
	 * 
	 * @param channelDirectorName
	 *            the value for fos_receive_order.CHANNEL_DIRECTOR_NAME
	 * @mbggenerated
	 */
	public void setChannelDirectorName(String channelDirectorName) {
		this.channelDirectorName = channelDirectorName == null ? null
				: channelDirectorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.C_UNIT
	 * 
	 * @return the value of fos_receive_order.C_UNIT
	 * @mbggenerated
	 */
	public BigDecimal getcUnit() {
		return cUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.C_UNIT
	 * 
	 * @param cUnit
	 *            the value for fos_receive_order.C_UNIT
	 * @mbggenerated
	 */
	public void setcUnit(BigDecimal cUnit) {
		this.cUnit = cUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.C_COUNT
	 * 
	 * @return the value of fos_receive_order.C_COUNT
	 * @mbggenerated
	 */
	public Integer getcCount() {
		return cCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.C_COUNT
	 * 
	 * @param cCount
	 *            the value for fos_receive_order.C_COUNT
	 * @mbggenerated
	 */
	public void setcCount(Integer cCount) {
		this.cCount = cCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.C_AMOUNT
	 * 
	 * @return the value of fos_receive_order.C_AMOUNT
	 * @mbggenerated
	 */
	public BigDecimal getcAmount() {
		return cAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.C_AMOUNT
	 * 
	 * @param cAmount
	 *            the value for fos_receive_order.C_AMOUNT
	 * @mbggenerated
	 */
	public void setcAmount(BigDecimal cAmount) {
		this.cAmount = cAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.SUB_AMOUNT
	 * 
	 * @return the value of fos_receive_order.SUB_AMOUNT
	 * @mbggenerated
	 */
	public BigDecimal getSubAmount() {
		return subAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.SUB_AMOUNT
	 * 
	 * @param subAmount
	 *            the value for fos_receive_order.SUB_AMOUNT
	 * @mbggenerated
	 */
	public void setSubAmount(BigDecimal subAmount) {
		this.subAmount = subAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.MEDIA_REBATE
	 * 
	 * @return the value of fos_receive_order.MEDIA_REBATE
	 * @mbggenerated
	 */
	public BigDecimal getMediaRebate() {
		return mediaRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.MEDIA_REBATE
	 * 
	 * @param mediaRebate
	 *            the value for fos_receive_order.MEDIA_REBATE
	 * @mbggenerated
	 */
	public void setMediaRebate(BigDecimal mediaRebate) {
		this.mediaRebate = mediaRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.OTHER_EXPENSE
	 * 
	 * @return the value of fos_receive_order.OTHER_EXPENSE
	 * @mbggenerated
	 */
	public BigDecimal getOtherExpense() {
		return otherExpense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.OTHER_EXPENSE
	 * 
	 * @param otherExpense
	 *            the value for fos_receive_order.OTHER_EXPENSE
	 * @mbggenerated
	 */
	public void setOtherExpense(BigDecimal otherExpense) {
		this.otherExpense = otherExpense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.CHANNEL_CUT
	 * 
	 * @return the value of fos_receive_order.CHANNEL_CUT
	 * @mbggenerated
	 */
	public BigDecimal getChannelCut() {
		return channelCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.CHANNEL_CUT
	 * 
	 * @param channelCut
	 *            the value for fos_receive_order.CHANNEL_CUT
	 * @mbggenerated
	 */
	public void setChannelCut(BigDecimal channelCut) {
		this.channelCut = channelCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.CHANNEL_ORDER_NAME
	 * 
	 * @return the value of fos_receive_order.CHANNEL_ORDER_NAME
	 * @mbggenerated
	 */
	public String getChannelOrderName() {
		return channelOrderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.CHANNEL_ORDER_NAME
	 * 
	 * @param channelOrderName
	 *            the value for fos_receive_order.CHANNEL_ORDER_NAME
	 * @mbggenerated
	 */
	public void setChannelOrderName(String channelOrderName) {
		this.channelOrderName = channelOrderName == null ? null
				: channelOrderName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.COMPANY
	 * 
	 * @return the value of fos_receive_order.COMPANY
	 * @mbggenerated
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.COMPANY
	 * 
	 * @param company
	 *            the value for fos_receive_order.COMPANY
	 * @mbggenerated
	 */
	public void setCompany(String company) {
		this.company = company == null ? null : company.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.MONEY
	 * 
	 * @return the value of fos_receive_order.MONEY
	 * @mbggenerated
	 */
	public BigDecimal getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.MONEY
	 * 
	 * @param money
	 *            the value for fos_receive_order.MONEY
	 * @mbggenerated
	 */
	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.DATA_TIME
	 * 
	 * @return the value of fos_receive_order.DATA_TIME
	 * @mbggenerated
	 */
	public Date getDataTime() {
		return dataTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.DATA_TIME
	 * 
	 * @param dataTime
	 *            the value for fos_receive_order.DATA_TIME
	 * @mbggenerated
	 */
	public void setDataTime(Date dataTime) {
		this.dataTime = dataTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.TICKET_CODE
	 * 
	 * @return the value of fos_receive_order.TICKET_CODE
	 * @mbggenerated
	 */
	public String getTicketCode() {
		return ticketCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.TICKET_CODE
	 * 
	 * @param ticketCode
	 *            the value for fos_receive_order.TICKET_CODE
	 * @mbggenerated
	 */
	public void setTicketCode(String ticketCode) {
		this.ticketCode = ticketCode == null ? null : ticketCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.TICKET_NUM
	 * 
	 * @return the value of fos_receive_order.TICKET_NUM
	 * @mbggenerated
	 */
	public String getTicketNum() {
		return ticketNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.TICKET_NUM
	 * 
	 * @param ticketNum
	 *            the value for fos_receive_order.TICKET_NUM
	 * @mbggenerated
	 */
	public void setTicketNum(String ticketNum) {
		this.ticketNum = ticketNum == null ? null : ticketNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.TICKET_TIME
	 * 
	 * @return the value of fos_receive_order.TICKET_TIME
	 * @mbggenerated
	 */
	public String getTicketTime() {
		return ticketTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.TICKET_TIME
	 * 
	 * @param ticketTime
	 *            the value for fos_receive_order.TICKET_TIME
	 * @mbggenerated
	 */
	public void setTicketTime(String ticketTime) {
		this.ticketTime = ticketTime == null ? null : ticketTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.STATUS
	 * 
	 * @return the value of fos_receive_order.STATUS
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.STATUS
	 * 
	 * @param status
	 *            the value for fos_receive_order.STATUS
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.PAY_MONEY
	 * 
	 * @return the value of fos_receive_order.PAY_MONEY
	 * @mbggenerated
	 */
	public Long getPayMoney() {
		return payMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.PAY_MONEY
	 * 
	 * @param payMoney
	 *            the value for fos_receive_order.PAY_MONEY
	 * @mbggenerated
	 */
	public void setPayMoney(Long payMoney) {
		this.payMoney = payMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.PAY_DATE
	 * 
	 * @return the value of fos_receive_order.PAY_DATE
	 * @mbggenerated
	 */
	public Date getPayDate() {
		return payDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.PAY_DATE
	 * 
	 * @param payDate
	 *            the value for fos_receive_order.PAY_DATE
	 * @mbggenerated
	 */
	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.ADVANCE_PAY
	 * 
	 * @return the value of fos_receive_order.ADVANCE_PAY
	 * @mbggenerated
	 */
	public BigDecimal getAdvancePay() {
		return advancePay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.ADVANCE_PAY
	 * 
	 * @param advancePay
	 *            the value for fos_receive_order.ADVANCE_PAY
	 * @mbggenerated
	 */
	public void setAdvancePay(BigDecimal advancePay) {
		this.advancePay = advancePay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fos_receive_order.CHANNEL_ORDER_ID
	 * 
	 * @return the value of fos_receive_order.CHANNEL_ORDER_ID
	 * @mbggenerated
	 */
	public Integer getChannelOrderId() {
		return channelOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fos_receive_order.CHANNEL_ORDER_ID
	 * 
	 * @param channelOrderId
	 *            the value for fos_receive_order.CHANNEL_ORDER_ID
	 * @mbggenerated
	 */
	public void setChannelOrderId(Integer channelOrderId) {
		this.channelOrderId = channelOrderId;
	}

	public Date getChannelTime() {
		return channelTime;
	}

	public void setChannelTime(Date channelTime) {
		this.channelTime = channelTime;
	}

	@Override
	public String toString() {
		return "FosReceiveOrderVo [id=" + id + ", ids=" + ids + ", channelId="
				+ channelId + ", channelName=" + channelName
				+ ", channelDirectorName=" + channelDirectorName + ", cUnit="
				+ cUnit + ", cCount=" + cCount + ", cAmount=" + cAmount
				+ ", subAmount=" + subAmount + ", mediaRebate=" + mediaRebate
				+ ", otherExpense=" + otherExpense + ", channelCut="
				+ channelCut + ", channelOrderName=" + channelOrderName
				+ ", company=" + company + ", money=" + money + ", dataTime="
				+ dataTime + ", ticketCode=" + ticketCode + ", ticketNum="
				+ ticketNum + ", ticketTime=" + ticketTime + ", status="
				+ status + ", payMoney=" + payMoney + ", payDate=" + payDate
				+ ", advancePay=" + advancePay + ", channelOrderId="
				+ channelOrderId + ", channelTime=" + channelTime
				+ ", advanceConsume=" + advanceConsume + "]";
	}

	@Override
	public boolean verify(String str) throws ImopanException {
		// TODO Auto-generated method stub
		return false;
	}

	private BigDecimal advanceConsume;
	private Date createTime;
	

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public BigDecimal getAdvanceConsume() {
		return advanceConsume;
	}

	public void setAdvanceConsume(BigDecimal advanceConsume) {
		this.advanceConsume = advanceConsume;
	}

}