package com.imopan.adv.platform.entity.fos;

import com.imopan.adv.platform.common.BaseBean;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FosAuditChannelMonth extends BaseBean implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.FOS_CHANNEL_MONTH_ID
	 * @mbggenerated
	 */
	private Integer fosChannelMonthId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.CHANNEL_SUBMIT_CONFIRM
	 * @mbggenerated
	 */
	private Date channelSubmitConfirm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.CHANNEL_UPDATE_C_COUNT_SUM
	 * @mbggenerated
	 */
	private Integer channelUpdateCCountSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.CHANNEL_UPDATE_C_AMOUNT_SUM
	 * @mbggenerated
	 */
	private BigDecimal channelUpdateCAmountSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.CHANNEL_UPDATE_MEDIA_REBATE
	 * @mbggenerated
	 */
	private BigDecimal channelUpdateMediaRebate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.CHANNEL_UPDATE_OTHER_EXPENSE
	 * @mbggenerated
	 */
	private BigDecimal channelUpdateOtherExpense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.CHANNEL_UPDATE_CHANNEL_CUT
	 * @mbggenerated
	 */
	private BigDecimal channelUpdateChannelCut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_STATUS
	 * @mbggenerated
	 */
	private Byte financialSubmitChannelStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.FINANCIAL_SUBMIT_C_COUNT_SUM
	 * @mbggenerated
	 */
	private Integer financialSubmitCCountSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.FINANCIAL_SUBMIT_C_AMOUNT_SUM
	 * @mbggenerated
	 */
	private BigDecimal financialSubmitCAmountSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.FINANCIAL_SUBMIT_MEDIA_REBATE
	 * @mbggenerated
	 */
	private BigDecimal financialSubmitMediaRebate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.FINANCIAL_SUBMIT_OTHER_EXPENSE
	 * @mbggenerated
	 */
	private BigDecimal financialSubmitOtherExpense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_CUT
	 * @mbggenerated
	 */
	private BigDecimal financialSubmitChannelCut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_DATE
	 * @mbggenerated
	 */
	private Date financialSubmitChannelDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME
	 * @mbggenerated
	 */
	private Integer financialSubmitChannelNotthroughTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON
	 * @mbggenerated
	 */
	private String financialSubmitChannelNotthroughReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_channel_month.RECEIVE_BILL_STATUS
	 * @mbggenerated
	 */
	private Byte receiveBillStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_audit_channel_month
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.ID
	 * @return  the value of fos_audit_channel_month.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.ID
	 * @param id  the value for fos_audit_channel_month.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.FOS_CHANNEL_MONTH_ID
	 * @return  the value of fos_audit_channel_month.FOS_CHANNEL_MONTH_ID
	 * @mbggenerated
	 */
	public Integer getFosChannelMonthId() {
		return fosChannelMonthId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.FOS_CHANNEL_MONTH_ID
	 * @param fosChannelMonthId  the value for fos_audit_channel_month.FOS_CHANNEL_MONTH_ID
	 * @mbggenerated
	 */
	public void setFosChannelMonthId(Integer fosChannelMonthId) {
		this.fosChannelMonthId = fosChannelMonthId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.CHANNEL_SUBMIT_CONFIRM
	 * @return  the value of fos_audit_channel_month.CHANNEL_SUBMIT_CONFIRM
	 * @mbggenerated
	 */
	public Date getChannelSubmitConfirm() {
		return channelSubmitConfirm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.CHANNEL_SUBMIT_CONFIRM
	 * @param channelSubmitConfirm  the value for fos_audit_channel_month.CHANNEL_SUBMIT_CONFIRM
	 * @mbggenerated
	 */
	public void setChannelSubmitConfirm(Date channelSubmitConfirm) {
		this.channelSubmitConfirm = channelSubmitConfirm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.CHANNEL_UPDATE_C_COUNT_SUM
	 * @return  the value of fos_audit_channel_month.CHANNEL_UPDATE_C_COUNT_SUM
	 * @mbggenerated
	 */
	public Integer getChannelUpdateCCountSum() {
		return channelUpdateCCountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.CHANNEL_UPDATE_C_COUNT_SUM
	 * @param channelUpdateCCountSum  the value for fos_audit_channel_month.CHANNEL_UPDATE_C_COUNT_SUM
	 * @mbggenerated
	 */
	public void setChannelUpdateCCountSum(Integer channelUpdateCCountSum) {
		this.channelUpdateCCountSum = channelUpdateCCountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.CHANNEL_UPDATE_C_AMOUNT_SUM
	 * @return  the value of fos_audit_channel_month.CHANNEL_UPDATE_C_AMOUNT_SUM
	 * @mbggenerated
	 */
	public BigDecimal getChannelUpdateCAmountSum() {
		return channelUpdateCAmountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.CHANNEL_UPDATE_C_AMOUNT_SUM
	 * @param channelUpdateCAmountSum  the value for fos_audit_channel_month.CHANNEL_UPDATE_C_AMOUNT_SUM
	 * @mbggenerated
	 */
	public void setChannelUpdateCAmountSum(BigDecimal channelUpdateCAmountSum) {
		this.channelUpdateCAmountSum = channelUpdateCAmountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.CHANNEL_UPDATE_MEDIA_REBATE
	 * @return  the value of fos_audit_channel_month.CHANNEL_UPDATE_MEDIA_REBATE
	 * @mbggenerated
	 */
	public BigDecimal getChannelUpdateMediaRebate() {
		return channelUpdateMediaRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.CHANNEL_UPDATE_MEDIA_REBATE
	 * @param channelUpdateMediaRebate  the value for fos_audit_channel_month.CHANNEL_UPDATE_MEDIA_REBATE
	 * @mbggenerated
	 */
	public void setChannelUpdateMediaRebate(BigDecimal channelUpdateMediaRebate) {
		this.channelUpdateMediaRebate = channelUpdateMediaRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.CHANNEL_UPDATE_OTHER_EXPENSE
	 * @return  the value of fos_audit_channel_month.CHANNEL_UPDATE_OTHER_EXPENSE
	 * @mbggenerated
	 */
	public BigDecimal getChannelUpdateOtherExpense() {
		return channelUpdateOtherExpense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.CHANNEL_UPDATE_OTHER_EXPENSE
	 * @param channelUpdateOtherExpense  the value for fos_audit_channel_month.CHANNEL_UPDATE_OTHER_EXPENSE
	 * @mbggenerated
	 */
	public void setChannelUpdateOtherExpense(
			BigDecimal channelUpdateOtherExpense) {
		this.channelUpdateOtherExpense = channelUpdateOtherExpense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.CHANNEL_UPDATE_CHANNEL_CUT
	 * @return  the value of fos_audit_channel_month.CHANNEL_UPDATE_CHANNEL_CUT
	 * @mbggenerated
	 */
	public BigDecimal getChannelUpdateChannelCut() {
		return channelUpdateChannelCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.CHANNEL_UPDATE_CHANNEL_CUT
	 * @param channelUpdateChannelCut  the value for fos_audit_channel_month.CHANNEL_UPDATE_CHANNEL_CUT
	 * @mbggenerated
	 */
	public void setChannelUpdateChannelCut(BigDecimal channelUpdateChannelCut) {
		this.channelUpdateChannelCut = channelUpdateChannelCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_STATUS
	 * @return  the value of fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_STATUS
	 * @mbggenerated
	 */
	public Byte getFinancialSubmitChannelStatus() {
		return financialSubmitChannelStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_STATUS
	 * @param financialSubmitChannelStatus  the value for fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_STATUS
	 * @mbggenerated
	 */
	public void setFinancialSubmitChannelStatus(
			Byte financialSubmitChannelStatus) {
		this.financialSubmitChannelStatus = financialSubmitChannelStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_C_COUNT_SUM
	 * @return  the value of fos_audit_channel_month.FINANCIAL_SUBMIT_C_COUNT_SUM
	 * @mbggenerated
	 */
	public Integer getFinancialSubmitCCountSum() {
		return financialSubmitCCountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_C_COUNT_SUM
	 * @param financialSubmitCCountSum  the value for fos_audit_channel_month.FINANCIAL_SUBMIT_C_COUNT_SUM
	 * @mbggenerated
	 */
	public void setFinancialSubmitCCountSum(Integer financialSubmitCCountSum) {
		this.financialSubmitCCountSum = financialSubmitCCountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_C_AMOUNT_SUM
	 * @return  the value of fos_audit_channel_month.FINANCIAL_SUBMIT_C_AMOUNT_SUM
	 * @mbggenerated
	 */
	public BigDecimal getFinancialSubmitCAmountSum() {
		return financialSubmitCAmountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_C_AMOUNT_SUM
	 * @param financialSubmitCAmountSum  the value for fos_audit_channel_month.FINANCIAL_SUBMIT_C_AMOUNT_SUM
	 * @mbggenerated
	 */
	public void setFinancialSubmitCAmountSum(
			BigDecimal financialSubmitCAmountSum) {
		this.financialSubmitCAmountSum = financialSubmitCAmountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_MEDIA_REBATE
	 * @return  the value of fos_audit_channel_month.FINANCIAL_SUBMIT_MEDIA_REBATE
	 * @mbggenerated
	 */
	public BigDecimal getFinancialSubmitMediaRebate() {
		return financialSubmitMediaRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_MEDIA_REBATE
	 * @param financialSubmitMediaRebate  the value for fos_audit_channel_month.FINANCIAL_SUBMIT_MEDIA_REBATE
	 * @mbggenerated
	 */
	public void setFinancialSubmitMediaRebate(
			BigDecimal financialSubmitMediaRebate) {
		this.financialSubmitMediaRebate = financialSubmitMediaRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_OTHER_EXPENSE
	 * @return  the value of fos_audit_channel_month.FINANCIAL_SUBMIT_OTHER_EXPENSE
	 * @mbggenerated
	 */
	public BigDecimal getFinancialSubmitOtherExpense() {
		return financialSubmitOtherExpense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_OTHER_EXPENSE
	 * @param financialSubmitOtherExpense  the value for fos_audit_channel_month.FINANCIAL_SUBMIT_OTHER_EXPENSE
	 * @mbggenerated
	 */
	public void setFinancialSubmitOtherExpense(
			BigDecimal financialSubmitOtherExpense) {
		this.financialSubmitOtherExpense = financialSubmitOtherExpense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_CUT
	 * @return  the value of fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_CUT
	 * @mbggenerated
	 */
	public BigDecimal getFinancialSubmitChannelCut() {
		return financialSubmitChannelCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_CUT
	 * @param financialSubmitChannelCut  the value for fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_CUT
	 * @mbggenerated
	 */
	public void setFinancialSubmitChannelCut(
			BigDecimal financialSubmitChannelCut) {
		this.financialSubmitChannelCut = financialSubmitChannelCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_DATE
	 * @return  the value of fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_DATE
	 * @mbggenerated
	 */
	public Date getFinancialSubmitChannelDate() {
		return financialSubmitChannelDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_DATE
	 * @param financialSubmitChannelDate  the value for fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_DATE
	 * @mbggenerated
	 */
	public void setFinancialSubmitChannelDate(Date financialSubmitChannelDate) {
		this.financialSubmitChannelDate = financialSubmitChannelDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME
	 * @return  the value of fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME
	 * @mbggenerated
	 */
	public Integer getFinancialSubmitChannelNotthroughTime() {
		return financialSubmitChannelNotthroughTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME
	 * @param financialSubmitChannelNotthroughTime  the value for fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME
	 * @mbggenerated
	 */
	public void setFinancialSubmitChannelNotthroughTime(
			Integer financialSubmitChannelNotthroughTime) {
		this.financialSubmitChannelNotthroughTime = financialSubmitChannelNotthroughTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON
	 * @return  the value of fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON
	 * @mbggenerated
	 */
	public String getFinancialSubmitChannelNotthroughReason() {
		return financialSubmitChannelNotthroughReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON
	 * @param financialSubmitChannelNotthroughReason  the value for fos_audit_channel_month.FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON
	 * @mbggenerated
	 */
	public void setFinancialSubmitChannelNotthroughReason(
			String financialSubmitChannelNotthroughReason) {
		this.financialSubmitChannelNotthroughReason = financialSubmitChannelNotthroughReason == null ? null
				: financialSubmitChannelNotthroughReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_channel_month.RECEIVE_BILL_STATUS
	 * @return  the value of fos_audit_channel_month.RECEIVE_BILL_STATUS
	 * @mbggenerated
	 */
	public Byte getReceiveBillStatus() {
		return receiveBillStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_channel_month.RECEIVE_BILL_STATUS
	 * @param receiveBillStatus  the value for fos_audit_channel_month.RECEIVE_BILL_STATUS
	 * @mbggenerated
	 */
	public void setReceiveBillStatus(Byte receiveBillStatus) {
		this.receiveBillStatus = receiveBillStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_month
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", fosChannelMonthId=").append(fosChannelMonthId);
		sb.append(", channelSubmitConfirm=").append(channelSubmitConfirm);
		sb.append(", channelUpdateCCountSum=").append(channelUpdateCCountSum);
		sb.append(", channelUpdateCAmountSum=").append(channelUpdateCAmountSum);
		sb.append(", channelUpdateMediaRebate=").append(
				channelUpdateMediaRebate);
		sb.append(", channelUpdateOtherExpense=").append(
				channelUpdateOtherExpense);
		sb.append(", channelUpdateChannelCut=").append(channelUpdateChannelCut);
		sb.append(", financialSubmitChannelStatus=").append(
				financialSubmitChannelStatus);
		sb.append(", financialSubmitCCountSum=").append(
				financialSubmitCCountSum);
		sb.append(", financialSubmitCAmountSum=").append(
				financialSubmitCAmountSum);
		sb.append(", financialSubmitMediaRebate=").append(
				financialSubmitMediaRebate);
		sb.append(", financialSubmitOtherExpense=").append(
				financialSubmitOtherExpense);
		sb.append(", financialSubmitChannelCut=").append(
				financialSubmitChannelCut);
		sb.append(", financialSubmitChannelDate=").append(
				financialSubmitChannelDate);
		sb.append(", financialSubmitChannelNotthroughTime=").append(
				financialSubmitChannelNotthroughTime);
		sb.append(", financialSubmitChannelNotthroughReason=").append(
				financialSubmitChannelNotthroughReason);
		sb.append(", receiveBillStatus=").append(receiveBillStatus);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}