package com.imopan.adv.platform.entity.fos;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class FosAuditChannelDayExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	protected Integer limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	protected Integer limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public FosAuditChannelDayExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public Integer getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public Integer getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOcDayIdIsNull() {
			addCriterion("OC_DAY_ID is null");
			return (Criteria) this;
		}

		public Criteria andOcDayIdIsNotNull() {
			addCriterion("OC_DAY_ID is not null");
			return (Criteria) this;
		}

		public Criteria andOcDayIdEqualTo(Integer value) {
			addCriterion("OC_DAY_ID =", value, "ocDayId");
			return (Criteria) this;
		}

		public Criteria andOcDayIdNotEqualTo(Integer value) {
			addCriterion("OC_DAY_ID <>", value, "ocDayId");
			return (Criteria) this;
		}

		public Criteria andOcDayIdGreaterThan(Integer value) {
			addCriterion("OC_DAY_ID >", value, "ocDayId");
			return (Criteria) this;
		}

		public Criteria andOcDayIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("OC_DAY_ID >=", value, "ocDayId");
			return (Criteria) this;
		}

		public Criteria andOcDayIdLessThan(Integer value) {
			addCriterion("OC_DAY_ID <", value, "ocDayId");
			return (Criteria) this;
		}

		public Criteria andOcDayIdLessThanOrEqualTo(Integer value) {
			addCriterion("OC_DAY_ID <=", value, "ocDayId");
			return (Criteria) this;
		}

		public Criteria andOcDayIdIn(List<Integer> values) {
			addCriterion("OC_DAY_ID in", values, "ocDayId");
			return (Criteria) this;
		}

		public Criteria andOcDayIdNotIn(List<Integer> values) {
			addCriterion("OC_DAY_ID not in", values, "ocDayId");
			return (Criteria) this;
		}

		public Criteria andOcDayIdBetween(Integer value1, Integer value2) {
			addCriterion("OC_DAY_ID between", value1, value2, "ocDayId");
			return (Criteria) this;
		}

		public Criteria andOcDayIdNotBetween(Integer value1, Integer value2) {
			addCriterion("OC_DAY_ID not between", value1, value2, "ocDayId");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmIsNull() {
			addCriterion("CHANNEL_SUBMIT_CONFIRM is null");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmIsNotNull() {
			addCriterion("CHANNEL_SUBMIT_CONFIRM is not null");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmEqualTo(Date value) {
			addCriterionForJDBCDate("CHANNEL_SUBMIT_CONFIRM =", value,
					"channelSubmitConfirm");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmNotEqualTo(Date value) {
			addCriterionForJDBCDate("CHANNEL_SUBMIT_CONFIRM <>", value,
					"channelSubmitConfirm");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmGreaterThan(Date value) {
			addCriterionForJDBCDate("CHANNEL_SUBMIT_CONFIRM >", value,
					"channelSubmitConfirm");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CHANNEL_SUBMIT_CONFIRM >=", value,
					"channelSubmitConfirm");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmLessThan(Date value) {
			addCriterionForJDBCDate("CHANNEL_SUBMIT_CONFIRM <", value,
					"channelSubmitConfirm");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CHANNEL_SUBMIT_CONFIRM <=", value,
					"channelSubmitConfirm");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmIn(List<Date> values) {
			addCriterionForJDBCDate("CHANNEL_SUBMIT_CONFIRM in", values,
					"channelSubmitConfirm");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmNotIn(List<Date> values) {
			addCriterionForJDBCDate("CHANNEL_SUBMIT_CONFIRM not in", values,
					"channelSubmitConfirm");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CHANNEL_SUBMIT_CONFIRM between", value1,
					value2, "channelSubmitConfirm");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitConfirmNotBetween(Date value1,
				Date value2) {
			addCriterionForJDBCDate("CHANNEL_SUBMIT_CONFIRM not between",
					value1, value2, "channelSubmitConfirm");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitIsNull() {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT is null");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitIsNotNull() {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT is not null");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitEqualTo(BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT =", value,
					"channelSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitNotEqualTo(BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT <>", value,
					"channelSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitGreaterThan(BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT >", value,
					"channelSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitGreaterThanOrEqualTo(
				BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT >=", value,
					"channelSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitLessThan(BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT <", value,
					"channelSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitLessThanOrEqualTo(
				BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT <=", value,
					"channelSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitIn(List<BigDecimal> values) {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT in", values,
					"channelSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitNotIn(List<BigDecimal> values) {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT not in", values,
					"channelSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT between", value1, value2,
					"channelSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitOuterunitNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("CHANNEL_SUBMIT_OUTERUNIT not between", value1,
					value2, "channelSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountIsNull() {
			addCriterion("CHANNEL_SUBMIT_CCOUNT is null");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountIsNotNull() {
			addCriterion("CHANNEL_SUBMIT_CCOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountEqualTo(Integer value) {
			addCriterion("CHANNEL_SUBMIT_CCOUNT =", value,
					"channelSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountNotEqualTo(Integer value) {
			addCriterion("CHANNEL_SUBMIT_CCOUNT <>", value,
					"channelSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountGreaterThan(Integer value) {
			addCriterion("CHANNEL_SUBMIT_CCOUNT >", value,
					"channelSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("CHANNEL_SUBMIT_CCOUNT >=", value,
					"channelSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountLessThan(Integer value) {
			addCriterion("CHANNEL_SUBMIT_CCOUNT <", value,
					"channelSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountLessThanOrEqualTo(Integer value) {
			addCriterion("CHANNEL_SUBMIT_CCOUNT <=", value,
					"channelSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountIn(List<Integer> values) {
			addCriterion("CHANNEL_SUBMIT_CCOUNT in", values,
					"channelSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountNotIn(List<Integer> values) {
			addCriterion("CHANNEL_SUBMIT_CCOUNT not in", values,
					"channelSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountBetween(Integer value1,
				Integer value2) {
			addCriterion("CHANNEL_SUBMIT_CCOUNT between", value1, value2,
					"channelSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCcountNotBetween(Integer value1,
				Integer value2) {
			addCriterion("CHANNEL_SUBMIT_CCOUNT not between", value1, value2,
					"channelSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountIsNull() {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountIsNotNull() {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountEqualTo(BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT =", value,
					"channelSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountNotEqualTo(BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT <>", value,
					"channelSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountGreaterThan(BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT >", value,
					"channelSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountGreaterThanOrEqualTo(
				BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT >=", value,
					"channelSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountLessThan(BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT <", value,
					"channelSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountLessThanOrEqualTo(
				BigDecimal value) {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT <=", value,
					"channelSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountIn(List<BigDecimal> values) {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT in", values,
					"channelSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountNotIn(List<BigDecimal> values) {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT not in", values,
					"channelSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT between", value1, value2,
					"channelSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andChannelSubmitCamountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("CHANNEL_SUBMIT_CAMOUNT not between", value1, value2,
					"channelSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusIsNull() {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusIsNotNull() {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusEqualTo(Byte value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS =", value,
					"financialSubmitChannelStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusNotEqualTo(Byte value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS <>", value,
					"financialSubmitChannelStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusGreaterThan(Byte value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS >", value,
					"financialSubmitChannelStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusGreaterThanOrEqualTo(
				Byte value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS >=", value,
					"financialSubmitChannelStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusLessThan(Byte value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS <", value,
					"financialSubmitChannelStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusLessThanOrEqualTo(
				Byte value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS <=", value,
					"financialSubmitChannelStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusIn(List<Byte> values) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS in", values,
					"financialSubmitChannelStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusNotIn(List<Byte> values) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS not in", values,
					"financialSubmitChannelStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusBetween(Byte value1,
				Byte value2) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS between", value1,
					value2, "financialSubmitChannelStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelStatusNotBetween(Byte value1,
				Byte value2) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_STATUS not between", value1,
					value2, "financialSubmitChannelStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitIsNull() {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT is null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitIsNotNull() {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT is not null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT =", value,
					"financialSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitNotEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT <>", value,
					"financialSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitGreaterThan(BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT >", value,
					"financialSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitGreaterThanOrEqualTo(
				BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT >=", value,
					"financialSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitLessThan(BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT <", value,
					"financialSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitLessThanOrEqualTo(
				BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT <=", value,
					"financialSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitIn(List<BigDecimal> values) {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT in", values,
					"financialSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitNotIn(List<BigDecimal> values) {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT not in", values,
					"financialSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT between", value1, value2,
					"financialSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitOuterunitNotBetween(
				BigDecimal value1, BigDecimal value2) {
			addCriterion("FINANCIAL_SUBMIT_OUTERUNIT not between", value1,
					value2, "financialSubmitOuterunit");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountIsNull() {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT is null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountIsNotNull() {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountEqualTo(Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT =", value,
					"financialSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountNotEqualTo(Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT <>", value,
					"financialSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountGreaterThan(Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT >", value,
					"financialSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountGreaterThanOrEqualTo(
				Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT >=", value,
					"financialSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountLessThan(Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT <", value,
					"financialSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountLessThanOrEqualTo(Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT <=", value,
					"financialSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountIn(List<Integer> values) {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT in", values,
					"financialSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountNotIn(List<Integer> values) {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT not in", values,
					"financialSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountBetween(Integer value1,
				Integer value2) {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT between", value1, value2,
					"financialSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCcountNotBetween(Integer value1,
				Integer value2) {
			addCriterion("FINANCIAL_SUBMIT_CCOUNT not between", value1, value2,
					"financialSubmitCcount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountIsNull() {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountIsNotNull() {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT =", value,
					"financialSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountNotEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT <>", value,
					"financialSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountGreaterThan(BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT >", value,
					"financialSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountGreaterThanOrEqualTo(
				BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT >=", value,
					"financialSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountLessThan(BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT <", value,
					"financialSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountLessThanOrEqualTo(
				BigDecimal value) {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT <=", value,
					"financialSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountIn(List<BigDecimal> values) {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT in", values,
					"financialSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountNotIn(List<BigDecimal> values) {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT not in", values,
					"financialSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT between", value1, value2,
					"financialSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitCamountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FINANCIAL_SUBMIT_CAMOUNT not between", value1,
					value2, "financialSubmitCamount");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateIsNull() {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_DATE is null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateIsNotNull() {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateEqualTo(Date value) {
			addCriterionForJDBCDate("FINANCIAL_SUBMIT_CHANNEL_DATE =", value,
					"financialSubmitChannelDate");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("FINANCIAL_SUBMIT_CHANNEL_DATE <>", value,
					"financialSubmitChannelDate");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateGreaterThan(Date value) {
			addCriterionForJDBCDate("FINANCIAL_SUBMIT_CHANNEL_DATE >", value,
					"financialSubmitChannelDate");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateGreaterThanOrEqualTo(
				Date value) {
			addCriterionForJDBCDate("FINANCIAL_SUBMIT_CHANNEL_DATE >=", value,
					"financialSubmitChannelDate");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateLessThan(Date value) {
			addCriterionForJDBCDate("FINANCIAL_SUBMIT_CHANNEL_DATE <", value,
					"financialSubmitChannelDate");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateLessThanOrEqualTo(
				Date value) {
			addCriterionForJDBCDate("FINANCIAL_SUBMIT_CHANNEL_DATE <=", value,
					"financialSubmitChannelDate");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateIn(List<Date> values) {
			addCriterionForJDBCDate("FINANCIAL_SUBMIT_CHANNEL_DATE in", values,
					"financialSubmitChannelDate");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("FINANCIAL_SUBMIT_CHANNEL_DATE not in",
					values, "financialSubmitChannelDate");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateBetween(Date value1,
				Date value2) {
			addCriterionForJDBCDate("FINANCIAL_SUBMIT_CHANNEL_DATE between",
					value1, value2, "financialSubmitChannelDate");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelDateNotBetween(Date value1,
				Date value2) {
			addCriterionForJDBCDate(
					"FINANCIAL_SUBMIT_CHANNEL_DATE not between", value1,
					value2, "financialSubmitChannelDate");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeIsNull() {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME is null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeIsNotNull() {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeEqualTo(
				Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME =", value,
					"financialSubmitChannelNotthroughTime");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeNotEqualTo(
				Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME <>", value,
					"financialSubmitChannelNotthroughTime");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeGreaterThan(
				Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME >", value,
					"financialSubmitChannelNotthroughTime");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeGreaterThanOrEqualTo(
				Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME >=", value,
					"financialSubmitChannelNotthroughTime");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeLessThan(
				Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME <", value,
					"financialSubmitChannelNotthroughTime");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeLessThanOrEqualTo(
				Integer value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME <=", value,
					"financialSubmitChannelNotthroughTime");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeIn(
				List<Integer> values) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME in", values,
					"financialSubmitChannelNotthroughTime");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeNotIn(
				List<Integer> values) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME not in",
					values, "financialSubmitChannelNotthroughTime");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeBetween(
				Integer value1, Integer value2) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME between",
					value1, value2, "financialSubmitChannelNotthroughTime");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughTimeNotBetween(
				Integer value1, Integer value2) {
			addCriterion(
					"FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_TIME not between",
					value1, value2, "financialSubmitChannelNotthroughTime");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonIsNull() {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON is null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonIsNotNull() {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON is not null");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonEqualTo(
				String value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON =", value,
					"financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonNotEqualTo(
				String value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON <>",
					value, "financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonGreaterThan(
				String value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON >", value,
					"financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonGreaterThanOrEqualTo(
				String value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON >=",
					value, "financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonLessThan(
				String value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON <", value,
					"financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonLessThanOrEqualTo(
				String value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON <=",
					value, "financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonLike(
				String value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON like",
					value, "financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonNotLike(
				String value) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON not like",
					value, "financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonIn(
				List<String> values) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON in",
					values, "financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonNotIn(
				List<String> values) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON not in",
					values, "financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonBetween(
				String value1, String value2) {
			addCriterion("FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON between",
					value1, value2, "financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonNotBetween(
				String value1, String value2) {
			addCriterion(
					"FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON not between",
					value1, value2, "financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountIsNull() {
			addCriterion("AVG_MONTH_CCOUNT is null");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountIsNotNull() {
			addCriterion("AVG_MONTH_CCOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountEqualTo(Integer value) {
			addCriterion("AVG_MONTH_CCOUNT =", value, "avgMonthCcount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountNotEqualTo(Integer value) {
			addCriterion("AVG_MONTH_CCOUNT <>", value, "avgMonthCcount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountGreaterThan(Integer value) {
			addCriterion("AVG_MONTH_CCOUNT >", value, "avgMonthCcount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("AVG_MONTH_CCOUNT >=", value, "avgMonthCcount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountLessThan(Integer value) {
			addCriterion("AVG_MONTH_CCOUNT <", value, "avgMonthCcount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountLessThanOrEqualTo(Integer value) {
			addCriterion("AVG_MONTH_CCOUNT <=", value, "avgMonthCcount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountIn(List<Integer> values) {
			addCriterion("AVG_MONTH_CCOUNT in", values, "avgMonthCcount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountNotIn(List<Integer> values) {
			addCriterion("AVG_MONTH_CCOUNT not in", values, "avgMonthCcount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountBetween(Integer value1, Integer value2) {
			addCriterion("AVG_MONTH_CCOUNT between", value1, value2,
					"avgMonthCcount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCcountNotBetween(Integer value1,
				Integer value2) {
			addCriterion("AVG_MONTH_CCOUNT not between", value1, value2,
					"avgMonthCcount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountIsNull() {
			addCriterion("AVG_MONTH_CAMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountIsNotNull() {
			addCriterion("AVG_MONTH_CAMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountEqualTo(BigDecimal value) {
			addCriterion("AVG_MONTH_CAMOUNT =", value, "avgMonthCamount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountNotEqualTo(BigDecimal value) {
			addCriterion("AVG_MONTH_CAMOUNT <>", value, "avgMonthCamount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountGreaterThan(BigDecimal value) {
			addCriterion("AVG_MONTH_CAMOUNT >", value, "avgMonthCamount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_MONTH_CAMOUNT >=", value, "avgMonthCamount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountLessThan(BigDecimal value) {
			addCriterion("AVG_MONTH_CAMOUNT <", value, "avgMonthCamount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_MONTH_CAMOUNT <=", value, "avgMonthCamount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountIn(List<BigDecimal> values) {
			addCriterion("AVG_MONTH_CAMOUNT in", values, "avgMonthCamount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountNotIn(List<BigDecimal> values) {
			addCriterion("AVG_MONTH_CAMOUNT not in", values, "avgMonthCamount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_MONTH_CAMOUNT between", value1, value2,
					"avgMonthCamount");
			return (Criteria) this;
		}

		public Criteria andAvgMonthCamountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_MONTH_CAMOUNT not between", value1, value2,
					"avgMonthCamount");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountIsNull() {
			addCriterion("AVG_SUB_AMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountIsNotNull() {
			addCriterion("AVG_SUB_AMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountEqualTo(BigDecimal value) {
			addCriterion("AVG_SUB_AMOUNT =", value, "avgSubAmount");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountNotEqualTo(BigDecimal value) {
			addCriterion("AVG_SUB_AMOUNT <>", value, "avgSubAmount");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountGreaterThan(BigDecimal value) {
			addCriterion("AVG_SUB_AMOUNT >", value, "avgSubAmount");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_SUB_AMOUNT >=", value, "avgSubAmount");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountLessThan(BigDecimal value) {
			addCriterion("AVG_SUB_AMOUNT <", value, "avgSubAmount");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_SUB_AMOUNT <=", value, "avgSubAmount");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountIn(List<BigDecimal> values) {
			addCriterion("AVG_SUB_AMOUNT in", values, "avgSubAmount");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountNotIn(List<BigDecimal> values) {
			addCriterion("AVG_SUB_AMOUNT not in", values, "avgSubAmount");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_SUB_AMOUNT between", value1, value2,
					"avgSubAmount");
			return (Criteria) this;
		}

		public Criteria andAvgSubAmountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_SUB_AMOUNT not between", value1, value2,
					"avgSubAmount");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateIsNull() {
			addCriterion("AVG_MEDIA_REBATE is null");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateIsNotNull() {
			addCriterion("AVG_MEDIA_REBATE is not null");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateEqualTo(BigDecimal value) {
			addCriterion("AVG_MEDIA_REBATE =", value, "avgMediaRebate");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateNotEqualTo(BigDecimal value) {
			addCriterion("AVG_MEDIA_REBATE <>", value, "avgMediaRebate");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateGreaterThan(BigDecimal value) {
			addCriterion("AVG_MEDIA_REBATE >", value, "avgMediaRebate");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_MEDIA_REBATE >=", value, "avgMediaRebate");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateLessThan(BigDecimal value) {
			addCriterion("AVG_MEDIA_REBATE <", value, "avgMediaRebate");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_MEDIA_REBATE <=", value, "avgMediaRebate");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateIn(List<BigDecimal> values) {
			addCriterion("AVG_MEDIA_REBATE in", values, "avgMediaRebate");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateNotIn(List<BigDecimal> values) {
			addCriterion("AVG_MEDIA_REBATE not in", values, "avgMediaRebate");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_MEDIA_REBATE between", value1, value2,
					"avgMediaRebate");
			return (Criteria) this;
		}

		public Criteria andAvgMediaRebateNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_MEDIA_REBATE not between", value1, value2,
					"avgMediaRebate");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseIsNull() {
			addCriterion("AVG_OTHER_EXPENSE is null");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseIsNotNull() {
			addCriterion("AVG_OTHER_EXPENSE is not null");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseEqualTo(BigDecimal value) {
			addCriterion("AVG_OTHER_EXPENSE =", value, "avgOtherExpense");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseNotEqualTo(BigDecimal value) {
			addCriterion("AVG_OTHER_EXPENSE <>", value, "avgOtherExpense");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseGreaterThan(BigDecimal value) {
			addCriterion("AVG_OTHER_EXPENSE >", value, "avgOtherExpense");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_OTHER_EXPENSE >=", value, "avgOtherExpense");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseLessThan(BigDecimal value) {
			addCriterion("AVG_OTHER_EXPENSE <", value, "avgOtherExpense");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_OTHER_EXPENSE <=", value, "avgOtherExpense");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseIn(List<BigDecimal> values) {
			addCriterion("AVG_OTHER_EXPENSE in", values, "avgOtherExpense");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseNotIn(List<BigDecimal> values) {
			addCriterion("AVG_OTHER_EXPENSE not in", values, "avgOtherExpense");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_OTHER_EXPENSE between", value1, value2,
					"avgOtherExpense");
			return (Criteria) this;
		}

		public Criteria andAvgOtherExpenseNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_OTHER_EXPENSE not between", value1, value2,
					"avgOtherExpense");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutIsNull() {
			addCriterion("AVG_CHANNEL_CUT is null");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutIsNotNull() {
			addCriterion("AVG_CHANNEL_CUT is not null");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutEqualTo(BigDecimal value) {
			addCriterion("AVG_CHANNEL_CUT =", value, "avgChannelCut");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutNotEqualTo(BigDecimal value) {
			addCriterion("AVG_CHANNEL_CUT <>", value, "avgChannelCut");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutGreaterThan(BigDecimal value) {
			addCriterion("AVG_CHANNEL_CUT >", value, "avgChannelCut");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_CHANNEL_CUT >=", value, "avgChannelCut");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutLessThan(BigDecimal value) {
			addCriterion("AVG_CHANNEL_CUT <", value, "avgChannelCut");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_CHANNEL_CUT <=", value, "avgChannelCut");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutIn(List<BigDecimal> values) {
			addCriterion("AVG_CHANNEL_CUT in", values, "avgChannelCut");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutNotIn(List<BigDecimal> values) {
			addCriterion("AVG_CHANNEL_CUT not in", values, "avgChannelCut");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_CHANNEL_CUT between", value1, value2,
					"avgChannelCut");
			return (Criteria) this;
		}

		public Criteria andAvgChannelCutNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_CHANNEL_CUT not between", value1, value2,
					"avgChannelCut");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyIsNull() {
			addCriterion("AVG_MONEY is null");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyIsNotNull() {
			addCriterion("AVG_MONEY is not null");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyEqualTo(BigDecimal value) {
			addCriterion("AVG_MONEY =", value, "avgMoney");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyNotEqualTo(BigDecimal value) {
			addCriterion("AVG_MONEY <>", value, "avgMoney");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyGreaterThan(BigDecimal value) {
			addCriterion("AVG_MONEY >", value, "avgMoney");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_MONEY >=", value, "avgMoney");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyLessThan(BigDecimal value) {
			addCriterion("AVG_MONEY <", value, "avgMoney");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_MONEY <=", value, "avgMoney");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyIn(List<BigDecimal> values) {
			addCriterion("AVG_MONEY in", values, "avgMoney");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyNotIn(List<BigDecimal> values) {
			addCriterion("AVG_MONEY not in", values, "avgMoney");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AVG_MONEY between", value1, value2, "avgMoney");
			return (Criteria) this;
		}

		public Criteria andAvgMoneyNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_MONEY not between", value1, value2, "avgMoney");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyIsNull() {
			addCriterion("AVG_PAY_MONEY is null");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyIsNotNull() {
			addCriterion("AVG_PAY_MONEY is not null");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyEqualTo(BigDecimal value) {
			addCriterion("AVG_PAY_MONEY =", value, "avgPayMoney");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyNotEqualTo(BigDecimal value) {
			addCriterion("AVG_PAY_MONEY <>", value, "avgPayMoney");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyGreaterThan(BigDecimal value) {
			addCriterion("AVG_PAY_MONEY >", value, "avgPayMoney");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_PAY_MONEY >=", value, "avgPayMoney");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyLessThan(BigDecimal value) {
			addCriterion("AVG_PAY_MONEY <", value, "avgPayMoney");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_PAY_MONEY <=", value, "avgPayMoney");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyIn(List<BigDecimal> values) {
			addCriterion("AVG_PAY_MONEY in", values, "avgPayMoney");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyNotIn(List<BigDecimal> values) {
			addCriterion("AVG_PAY_MONEY not in", values, "avgPayMoney");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_PAY_MONEY between", value1, value2, "avgPayMoney");
			return (Criteria) this;
		}

		public Criteria andAvgPayMoneyNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_PAY_MONEY not between", value1, value2,
					"avgPayMoney");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusIsNull() {
			addCriterion("CHANNEL_MONTH_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusIsNotNull() {
			addCriterion("CHANNEL_MONTH_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusEqualTo(Byte value) {
			addCriterion("CHANNEL_MONTH_STATUS =", value, "channelMonthStatus");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusNotEqualTo(Byte value) {
			addCriterion("CHANNEL_MONTH_STATUS <>", value, "channelMonthStatus");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusGreaterThan(Byte value) {
			addCriterion("CHANNEL_MONTH_STATUS >", value, "channelMonthStatus");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("CHANNEL_MONTH_STATUS >=", value, "channelMonthStatus");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusLessThan(Byte value) {
			addCriterion("CHANNEL_MONTH_STATUS <", value, "channelMonthStatus");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusLessThanOrEqualTo(Byte value) {
			addCriterion("CHANNEL_MONTH_STATUS <=", value, "channelMonthStatus");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusIn(List<Byte> values) {
			addCriterion("CHANNEL_MONTH_STATUS in", values,
					"channelMonthStatus");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusNotIn(List<Byte> values) {
			addCriterion("CHANNEL_MONTH_STATUS not in", values,
					"channelMonthStatus");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusBetween(Byte value1, Byte value2) {
			addCriterion("CHANNEL_MONTH_STATUS between", value1, value2,
					"channelMonthStatus");
			return (Criteria) this;
		}

		public Criteria andChannelMonthStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("CHANNEL_MONTH_STATUS not between", value1, value2,
					"channelMonthStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusIsNull() {
			addCriterion("FINANCIAL_RECEIVE_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusIsNotNull() {
			addCriterion("FINANCIAL_RECEIVE_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusEqualTo(Byte value) {
			addCriterion("FINANCIAL_RECEIVE_STATUS =", value,
					"financialReceiveStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusNotEqualTo(Byte value) {
			addCriterion("FINANCIAL_RECEIVE_STATUS <>", value,
					"financialReceiveStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusGreaterThan(Byte value) {
			addCriterion("FINANCIAL_RECEIVE_STATUS >", value,
					"financialReceiveStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("FINANCIAL_RECEIVE_STATUS >=", value,
					"financialReceiveStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusLessThan(Byte value) {
			addCriterion("FINANCIAL_RECEIVE_STATUS <", value,
					"financialReceiveStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusLessThanOrEqualTo(Byte value) {
			addCriterion("FINANCIAL_RECEIVE_STATUS <=", value,
					"financialReceiveStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusIn(List<Byte> values) {
			addCriterion("FINANCIAL_RECEIVE_STATUS in", values,
					"financialReceiveStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusNotIn(List<Byte> values) {
			addCriterion("FINANCIAL_RECEIVE_STATUS not in", values,
					"financialReceiveStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusBetween(Byte value1,
				Byte value2) {
			addCriterion("FINANCIAL_RECEIVE_STATUS between", value1, value2,
					"financialReceiveStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialReceiveStatusNotBetween(Byte value1,
				Byte value2) {
			addCriterion("FINANCIAL_RECEIVE_STATUS not between", value1,
					value2, "financialReceiveStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusIsNull() {
			addCriterion("FINANCIAL_PAY_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusIsNotNull() {
			addCriterion("FINANCIAL_PAY_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusEqualTo(Byte value) {
			addCriterion("FINANCIAL_PAY_STATUS =", value, "financialPayStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusNotEqualTo(Byte value) {
			addCriterion("FINANCIAL_PAY_STATUS <>", value, "financialPayStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusGreaterThan(Byte value) {
			addCriterion("FINANCIAL_PAY_STATUS >", value, "financialPayStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("FINANCIAL_PAY_STATUS >=", value, "financialPayStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusLessThan(Byte value) {
			addCriterion("FINANCIAL_PAY_STATUS <", value, "financialPayStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusLessThanOrEqualTo(Byte value) {
			addCriterion("FINANCIAL_PAY_STATUS <=", value, "financialPayStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusIn(List<Byte> values) {
			addCriterion("FINANCIAL_PAY_STATUS in", values,
					"financialPayStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusNotIn(List<Byte> values) {
			addCriterion("FINANCIAL_PAY_STATUS not in", values,
					"financialPayStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusBetween(Byte value1, Byte value2) {
			addCriterion("FINANCIAL_PAY_STATUS between", value1, value2,
					"financialPayStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialPayStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("FINANCIAL_PAY_STATUS not between", value1, value2,
					"financialPayStatus");
			return (Criteria) this;
		}

		public Criteria andFinancialSubmitChannelNotthroughReasonLikeInsensitive(
				String value) {
			addCriterion(
					"upper(FINANCIAL_SUBMIT_CHANNEL_NOTTHROUGH_REASON) like",
					value.toUpperCase(),
					"financialSubmitChannelNotthroughReason");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fos_audit_channel_day
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}