package com.imopan.adv.platform.entity.fos;

import com.imopan.adv.platform.common.BaseBean;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FosAuditOrderMonth extends BaseBean implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.FOS_ORDER_MONTH_ID
	 * @mbggenerated
	 */
	private Integer fosOrderMonthId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.ORDER_SUBMIT_CONFIRM
	 * @mbggenerated
	 */
	private Date orderSubmitConfirm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.ORDER_UPDATE_O_COUNT
	 * @mbggenerated
	 */
	private Integer orderUpdateOCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.ORDER_UPDATE_O_AMOUNT
	 * @mbggenerated
	 */
	private BigDecimal orderUpdateOAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.ORDER_UPDATE_CUT
	 * @mbggenerated
	 */
	private BigDecimal orderUpdateCut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.ORDER_UPDATE_SALE_REBATE
	 * @mbggenerated
	 */
	private BigDecimal orderUpdateSaleRebate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_STATUS
	 * @mbggenerated
	 */
	private Byte financialSubmitOrderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.FINANCIAL_SUBMIT_O_COUNT
	 * @mbggenerated
	 */
	private Integer financialSubmitOCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.FINANCIAL_SUBMIT_O_AMOUNT
	 * @mbggenerated
	 */
	private BigDecimal financialSubmitOAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.FINANCIAL_SUBMIT_CUT
	 * @mbggenerated
	 */
	private BigDecimal financialSubmitCut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.FINANCIAL_SUBMIT_SALE_REBATE
	 * @mbggenerated
	 */
	private BigDecimal financialSubmitSaleRebate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_DATE
	 * @mbggenerated
	 */
	private Date financialSubmitOrderDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_NOTTHROUGH_TIME
	 * @mbggenerated
	 */
	private Integer financialSubmitOrderNotthroughTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_NOTTHROUGH_REASON
	 * @mbggenerated
	 */
	private String financialSubmitOrderNotthroughReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_order_month.DRAW_BILL_STATUS
	 * @mbggenerated
	 */
	private Byte drawBillStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.ID
	 * @return  the value of fos_audit_order_month.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.ID
	 * @param id  the value for fos_audit_order_month.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.FOS_ORDER_MONTH_ID
	 * @return  the value of fos_audit_order_month.FOS_ORDER_MONTH_ID
	 * @mbggenerated
	 */
	public Integer getFosOrderMonthId() {
		return fosOrderMonthId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.FOS_ORDER_MONTH_ID
	 * @param fosOrderMonthId  the value for fos_audit_order_month.FOS_ORDER_MONTH_ID
	 * @mbggenerated
	 */
	public void setFosOrderMonthId(Integer fosOrderMonthId) {
		this.fosOrderMonthId = fosOrderMonthId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.ORDER_SUBMIT_CONFIRM
	 * @return  the value of fos_audit_order_month.ORDER_SUBMIT_CONFIRM
	 * @mbggenerated
	 */
	public Date getOrderSubmitConfirm() {
		return orderSubmitConfirm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.ORDER_SUBMIT_CONFIRM
	 * @param orderSubmitConfirm  the value for fos_audit_order_month.ORDER_SUBMIT_CONFIRM
	 * @mbggenerated
	 */
	public void setOrderSubmitConfirm(Date orderSubmitConfirm) {
		this.orderSubmitConfirm = orderSubmitConfirm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.ORDER_UPDATE_O_COUNT
	 * @return  the value of fos_audit_order_month.ORDER_UPDATE_O_COUNT
	 * @mbggenerated
	 */
	public Integer getOrderUpdateOCount() {
		return orderUpdateOCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.ORDER_UPDATE_O_COUNT
	 * @param orderUpdateOCount  the value for fos_audit_order_month.ORDER_UPDATE_O_COUNT
	 * @mbggenerated
	 */
	public void setOrderUpdateOCount(Integer orderUpdateOCount) {
		this.orderUpdateOCount = orderUpdateOCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.ORDER_UPDATE_O_AMOUNT
	 * @return  the value of fos_audit_order_month.ORDER_UPDATE_O_AMOUNT
	 * @mbggenerated
	 */
	public BigDecimal getOrderUpdateOAmount() {
		return orderUpdateOAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.ORDER_UPDATE_O_AMOUNT
	 * @param orderUpdateOAmount  the value for fos_audit_order_month.ORDER_UPDATE_O_AMOUNT
	 * @mbggenerated
	 */
	public void setOrderUpdateOAmount(BigDecimal orderUpdateOAmount) {
		this.orderUpdateOAmount = orderUpdateOAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.ORDER_UPDATE_CUT
	 * @return  the value of fos_audit_order_month.ORDER_UPDATE_CUT
	 * @mbggenerated
	 */
	public BigDecimal getOrderUpdateCut() {
		return orderUpdateCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.ORDER_UPDATE_CUT
	 * @param orderUpdateCut  the value for fos_audit_order_month.ORDER_UPDATE_CUT
	 * @mbggenerated
	 */
	public void setOrderUpdateCut(BigDecimal orderUpdateCut) {
		this.orderUpdateCut = orderUpdateCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.ORDER_UPDATE_SALE_REBATE
	 * @return  the value of fos_audit_order_month.ORDER_UPDATE_SALE_REBATE
	 * @mbggenerated
	 */
	public BigDecimal getOrderUpdateSaleRebate() {
		return orderUpdateSaleRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.ORDER_UPDATE_SALE_REBATE
	 * @param orderUpdateSaleRebate  the value for fos_audit_order_month.ORDER_UPDATE_SALE_REBATE
	 * @mbggenerated
	 */
	public void setOrderUpdateSaleRebate(BigDecimal orderUpdateSaleRebate) {
		this.orderUpdateSaleRebate = orderUpdateSaleRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_STATUS
	 * @return  the value of fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_STATUS
	 * @mbggenerated
	 */
	public Byte getFinancialSubmitOrderStatus() {
		return financialSubmitOrderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_STATUS
	 * @param financialSubmitOrderStatus  the value for fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_STATUS
	 * @mbggenerated
	 */
	public void setFinancialSubmitOrderStatus(Byte financialSubmitOrderStatus) {
		this.financialSubmitOrderStatus = financialSubmitOrderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_O_COUNT
	 * @return  the value of fos_audit_order_month.FINANCIAL_SUBMIT_O_COUNT
	 * @mbggenerated
	 */
	public Integer getFinancialSubmitOCount() {
		return financialSubmitOCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_O_COUNT
	 * @param financialSubmitOCount  the value for fos_audit_order_month.FINANCIAL_SUBMIT_O_COUNT
	 * @mbggenerated
	 */
	public void setFinancialSubmitOCount(Integer financialSubmitOCount) {
		this.financialSubmitOCount = financialSubmitOCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_O_AMOUNT
	 * @return  the value of fos_audit_order_month.FINANCIAL_SUBMIT_O_AMOUNT
	 * @mbggenerated
	 */
	public BigDecimal getFinancialSubmitOAmount() {
		return financialSubmitOAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_O_AMOUNT
	 * @param financialSubmitOAmount  the value for fos_audit_order_month.FINANCIAL_SUBMIT_O_AMOUNT
	 * @mbggenerated
	 */
	public void setFinancialSubmitOAmount(BigDecimal financialSubmitOAmount) {
		this.financialSubmitOAmount = financialSubmitOAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_CUT
	 * @return  the value of fos_audit_order_month.FINANCIAL_SUBMIT_CUT
	 * @mbggenerated
	 */
	public BigDecimal getFinancialSubmitCut() {
		return financialSubmitCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_CUT
	 * @param financialSubmitCut  the value for fos_audit_order_month.FINANCIAL_SUBMIT_CUT
	 * @mbggenerated
	 */
	public void setFinancialSubmitCut(BigDecimal financialSubmitCut) {
		this.financialSubmitCut = financialSubmitCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_SALE_REBATE
	 * @return  the value of fos_audit_order_month.FINANCIAL_SUBMIT_SALE_REBATE
	 * @mbggenerated
	 */
	public BigDecimal getFinancialSubmitSaleRebate() {
		return financialSubmitSaleRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_SALE_REBATE
	 * @param financialSubmitSaleRebate  the value for fos_audit_order_month.FINANCIAL_SUBMIT_SALE_REBATE
	 * @mbggenerated
	 */
	public void setFinancialSubmitSaleRebate(
			BigDecimal financialSubmitSaleRebate) {
		this.financialSubmitSaleRebate = financialSubmitSaleRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_DATE
	 * @return  the value of fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_DATE
	 * @mbggenerated
	 */
	public Date getFinancialSubmitOrderDate() {
		return financialSubmitOrderDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_DATE
	 * @param financialSubmitOrderDate  the value for fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_DATE
	 * @mbggenerated
	 */
	public void setFinancialSubmitOrderDate(Date financialSubmitOrderDate) {
		this.financialSubmitOrderDate = financialSubmitOrderDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_NOTTHROUGH_TIME
	 * @return  the value of fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_NOTTHROUGH_TIME
	 * @mbggenerated
	 */
	public Integer getFinancialSubmitOrderNotthroughTime() {
		return financialSubmitOrderNotthroughTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_NOTTHROUGH_TIME
	 * @param financialSubmitOrderNotthroughTime  the value for fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_NOTTHROUGH_TIME
	 * @mbggenerated
	 */
	public void setFinancialSubmitOrderNotthroughTime(
			Integer financialSubmitOrderNotthroughTime) {
		this.financialSubmitOrderNotthroughTime = financialSubmitOrderNotthroughTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_NOTTHROUGH_REASON
	 * @return  the value of fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_NOTTHROUGH_REASON
	 * @mbggenerated
	 */
	public String getFinancialSubmitOrderNotthroughReason() {
		return financialSubmitOrderNotthroughReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_NOTTHROUGH_REASON
	 * @param financialSubmitOrderNotthroughReason  the value for fos_audit_order_month.FINANCIAL_SUBMIT_ORDER_NOTTHROUGH_REASON
	 * @mbggenerated
	 */
	public void setFinancialSubmitOrderNotthroughReason(
			String financialSubmitOrderNotthroughReason) {
		this.financialSubmitOrderNotthroughReason = financialSubmitOrderNotthroughReason == null ? null
				: financialSubmitOrderNotthroughReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_order_month.DRAW_BILL_STATUS
	 * @return  the value of fos_audit_order_month.DRAW_BILL_STATUS
	 * @mbggenerated
	 */
	public Byte getDrawBillStatus() {
		return drawBillStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_order_month.DRAW_BILL_STATUS
	 * @param drawBillStatus  the value for fos_audit_order_month.DRAW_BILL_STATUS
	 * @mbggenerated
	 */
	public void setDrawBillStatus(Byte drawBillStatus) {
		this.drawBillStatus = drawBillStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", fosOrderMonthId=").append(fosOrderMonthId);
		sb.append(", orderSubmitConfirm=").append(orderSubmitConfirm);
		sb.append(", orderUpdateOCount=").append(orderUpdateOCount);
		sb.append(", orderUpdateOAmount=").append(orderUpdateOAmount);
		sb.append(", orderUpdateCut=").append(orderUpdateCut);
		sb.append(", orderUpdateSaleRebate=").append(orderUpdateSaleRebate);
		sb.append(", financialSubmitOrderStatus=").append(
				financialSubmitOrderStatus);
		sb.append(", financialSubmitOCount=").append(financialSubmitOCount);
		sb.append(", financialSubmitOAmount=").append(financialSubmitOAmount);
		sb.append(", financialSubmitCut=").append(financialSubmitCut);
		sb.append(", financialSubmitSaleRebate=").append(
				financialSubmitSaleRebate);
		sb.append(", financialSubmitOrderDate=").append(
				financialSubmitOrderDate);
		sb.append(", financialSubmitOrderNotthroughTime=").append(
				financialSubmitOrderNotthroughTime);
		sb.append(", financialSubmitOrderNotthroughReason=").append(
				financialSubmitOrderNotthroughReason);
		sb.append(", drawBillStatus=").append(drawBillStatus);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}