package com.imopan.adv.platform.entity.fos;

import com.imopan.adv.platform.common.BaseBean;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FosAuditCpDay extends BaseBean implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.OC_DAY_ID
	 * @mbggenerated
	 */
	private Integer ocDayId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.ORDER_SUBMIT_CONFIRM
	 * @mbggenerated
	 */
	private Date orderSubmitConfirm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.CP_SUBMIT_PAYUNIT
	 * @mbggenerated
	 */
	private BigDecimal cpSubmitPayunit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.CP_SUBMIT_OCOUNT
	 * @mbggenerated
	 */
	private Integer cpSubmitOcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.CP_SUBMIT_OAMOUNT
	 * @mbggenerated
	 */
	private BigDecimal cpSubmitOamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_STATUS
	 * @mbggenerated
	 */
	private Byte financialSubmitCpStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.FINANCIAL_SUBMIT_PAYUNIT
	 * @mbggenerated
	 */
	private BigDecimal financialSubmitPayunit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.FINANCIAL_SUBMIT_OCOUNT
	 * @mbggenerated
	 */
	private Integer financialSubmitOcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.FINANCIAL_SUBMIT_OAMOUNT
	 * @mbggenerated
	 */
	private BigDecimal financialSubmitOamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_DATE
	 * @mbggenerated
	 */
	private Date financialSubmitCpDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_NOTTHROUGH_TIME
	 * @mbggenerated
	 */
	private Integer financialSubmitCpNotthroughTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_NOTTHROUGH_REASON
	 * @mbggenerated
	 */
	private String financialSubmitCpNotthroughReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.AVG_MONTH_OCOUNT
	 * @mbggenerated
	 */
	private Integer avgMonthOcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.AVG_MONTH_OAMOUNT
	 * @mbggenerated
	 */
	private BigDecimal avgMonthOamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.AVG_CUT
	 * @mbggenerated
	 */
	private BigDecimal avgCut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.AVG_SALE_REBATE
	 * @mbggenerated
	 */
	private BigDecimal avgSaleRebate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.AVG_MONEY
	 * @mbggenerated
	 */
	private BigDecimal avgMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.AVG_RETURN_MONEY
	 * @mbggenerated
	 */
	private BigDecimal avgReturnMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.ORDER_MONTH_STATUS
	 * @mbggenerated
	 */
	private Byte orderMonthStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.FINANCIAL_DRAWBILL_STATUS
	 * @mbggenerated
	 */
	private Byte financialDrawbillStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fos_audit_cp_day.FINANCIAL_RECEIPT_STATUS
	 * @mbggenerated
	 */
	private Byte financialReceiptStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_audit_cp_day
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.ID
	 * @return  the value of fos_audit_cp_day.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.ID
	 * @param id  the value for fos_audit_cp_day.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.OC_DAY_ID
	 * @return  the value of fos_audit_cp_day.OC_DAY_ID
	 * @mbggenerated
	 */
	public Integer getOcDayId() {
		return ocDayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.OC_DAY_ID
	 * @param ocDayId  the value for fos_audit_cp_day.OC_DAY_ID
	 * @mbggenerated
	 */
	public void setOcDayId(Integer ocDayId) {
		this.ocDayId = ocDayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.ORDER_SUBMIT_CONFIRM
	 * @return  the value of fos_audit_cp_day.ORDER_SUBMIT_CONFIRM
	 * @mbggenerated
	 */
	public Date getOrderSubmitConfirm() {
		return orderSubmitConfirm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.ORDER_SUBMIT_CONFIRM
	 * @param orderSubmitConfirm  the value for fos_audit_cp_day.ORDER_SUBMIT_CONFIRM
	 * @mbggenerated
	 */
	public void setOrderSubmitConfirm(Date orderSubmitConfirm) {
		this.orderSubmitConfirm = orderSubmitConfirm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.CP_SUBMIT_PAYUNIT
	 * @return  the value of fos_audit_cp_day.CP_SUBMIT_PAYUNIT
	 * @mbggenerated
	 */
	public BigDecimal getCpSubmitPayunit() {
		return cpSubmitPayunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.CP_SUBMIT_PAYUNIT
	 * @param cpSubmitPayunit  the value for fos_audit_cp_day.CP_SUBMIT_PAYUNIT
	 * @mbggenerated
	 */
	public void setCpSubmitPayunit(BigDecimal cpSubmitPayunit) {
		this.cpSubmitPayunit = cpSubmitPayunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.CP_SUBMIT_OCOUNT
	 * @return  the value of fos_audit_cp_day.CP_SUBMIT_OCOUNT
	 * @mbggenerated
	 */
	public Integer getCpSubmitOcount() {
		return cpSubmitOcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.CP_SUBMIT_OCOUNT
	 * @param cpSubmitOcount  the value for fos_audit_cp_day.CP_SUBMIT_OCOUNT
	 * @mbggenerated
	 */
	public void setCpSubmitOcount(Integer cpSubmitOcount) {
		this.cpSubmitOcount = cpSubmitOcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.CP_SUBMIT_OAMOUNT
	 * @return  the value of fos_audit_cp_day.CP_SUBMIT_OAMOUNT
	 * @mbggenerated
	 */
	public BigDecimal getCpSubmitOamount() {
		return cpSubmitOamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.CP_SUBMIT_OAMOUNT
	 * @param cpSubmitOamount  the value for fos_audit_cp_day.CP_SUBMIT_OAMOUNT
	 * @mbggenerated
	 */
	public void setCpSubmitOamount(BigDecimal cpSubmitOamount) {
		this.cpSubmitOamount = cpSubmitOamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_STATUS
	 * @return  the value of fos_audit_cp_day.FINANCIAL_SUBMIT_CP_STATUS
	 * @mbggenerated
	 */
	public Byte getFinancialSubmitCpStatus() {
		return financialSubmitCpStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_STATUS
	 * @param financialSubmitCpStatus  the value for fos_audit_cp_day.FINANCIAL_SUBMIT_CP_STATUS
	 * @mbggenerated
	 */
	public void setFinancialSubmitCpStatus(Byte financialSubmitCpStatus) {
		this.financialSubmitCpStatus = financialSubmitCpStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_PAYUNIT
	 * @return  the value of fos_audit_cp_day.FINANCIAL_SUBMIT_PAYUNIT
	 * @mbggenerated
	 */
	public BigDecimal getFinancialSubmitPayunit() {
		return financialSubmitPayunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_PAYUNIT
	 * @param financialSubmitPayunit  the value for fos_audit_cp_day.FINANCIAL_SUBMIT_PAYUNIT
	 * @mbggenerated
	 */
	public void setFinancialSubmitPayunit(BigDecimal financialSubmitPayunit) {
		this.financialSubmitPayunit = financialSubmitPayunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_OCOUNT
	 * @return  the value of fos_audit_cp_day.FINANCIAL_SUBMIT_OCOUNT
	 * @mbggenerated
	 */
	public Integer getFinancialSubmitOcount() {
		return financialSubmitOcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_OCOUNT
	 * @param financialSubmitOcount  the value for fos_audit_cp_day.FINANCIAL_SUBMIT_OCOUNT
	 * @mbggenerated
	 */
	public void setFinancialSubmitOcount(Integer financialSubmitOcount) {
		this.financialSubmitOcount = financialSubmitOcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_OAMOUNT
	 * @return  the value of fos_audit_cp_day.FINANCIAL_SUBMIT_OAMOUNT
	 * @mbggenerated
	 */
	public BigDecimal getFinancialSubmitOamount() {
		return financialSubmitOamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_OAMOUNT
	 * @param financialSubmitOamount  the value for fos_audit_cp_day.FINANCIAL_SUBMIT_OAMOUNT
	 * @mbggenerated
	 */
	public void setFinancialSubmitOamount(BigDecimal financialSubmitOamount) {
		this.financialSubmitOamount = financialSubmitOamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_DATE
	 * @return  the value of fos_audit_cp_day.FINANCIAL_SUBMIT_CP_DATE
	 * @mbggenerated
	 */
	public Date getFinancialSubmitCpDate() {
		return financialSubmitCpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_DATE
	 * @param financialSubmitCpDate  the value for fos_audit_cp_day.FINANCIAL_SUBMIT_CP_DATE
	 * @mbggenerated
	 */
	public void setFinancialSubmitCpDate(Date financialSubmitCpDate) {
		this.financialSubmitCpDate = financialSubmitCpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_NOTTHROUGH_TIME
	 * @return  the value of fos_audit_cp_day.FINANCIAL_SUBMIT_CP_NOTTHROUGH_TIME
	 * @mbggenerated
	 */
	public Integer getFinancialSubmitCpNotthroughTime() {
		return financialSubmitCpNotthroughTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_NOTTHROUGH_TIME
	 * @param financialSubmitCpNotthroughTime  the value for fos_audit_cp_day.FINANCIAL_SUBMIT_CP_NOTTHROUGH_TIME
	 * @mbggenerated
	 */
	public void setFinancialSubmitCpNotthroughTime(
			Integer financialSubmitCpNotthroughTime) {
		this.financialSubmitCpNotthroughTime = financialSubmitCpNotthroughTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_NOTTHROUGH_REASON
	 * @return  the value of fos_audit_cp_day.FINANCIAL_SUBMIT_CP_NOTTHROUGH_REASON
	 * @mbggenerated
	 */
	public String getFinancialSubmitCpNotthroughReason() {
		return financialSubmitCpNotthroughReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.FINANCIAL_SUBMIT_CP_NOTTHROUGH_REASON
	 * @param financialSubmitCpNotthroughReason  the value for fos_audit_cp_day.FINANCIAL_SUBMIT_CP_NOTTHROUGH_REASON
	 * @mbggenerated
	 */
	public void setFinancialSubmitCpNotthroughReason(
			String financialSubmitCpNotthroughReason) {
		this.financialSubmitCpNotthroughReason = financialSubmitCpNotthroughReason == null ? null
				: financialSubmitCpNotthroughReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.AVG_MONTH_OCOUNT
	 * @return  the value of fos_audit_cp_day.AVG_MONTH_OCOUNT
	 * @mbggenerated
	 */
	public Integer getAvgMonthOcount() {
		return avgMonthOcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.AVG_MONTH_OCOUNT
	 * @param avgMonthOcount  the value for fos_audit_cp_day.AVG_MONTH_OCOUNT
	 * @mbggenerated
	 */
	public void setAvgMonthOcount(Integer avgMonthOcount) {
		this.avgMonthOcount = avgMonthOcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.AVG_MONTH_OAMOUNT
	 * @return  the value of fos_audit_cp_day.AVG_MONTH_OAMOUNT
	 * @mbggenerated
	 */
	public BigDecimal getAvgMonthOamount() {
		return avgMonthOamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.AVG_MONTH_OAMOUNT
	 * @param avgMonthOamount  the value for fos_audit_cp_day.AVG_MONTH_OAMOUNT
	 * @mbggenerated
	 */
	public void setAvgMonthOamount(BigDecimal avgMonthOamount) {
		this.avgMonthOamount = avgMonthOamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.AVG_CUT
	 * @return  the value of fos_audit_cp_day.AVG_CUT
	 * @mbggenerated
	 */
	public BigDecimal getAvgCut() {
		return avgCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.AVG_CUT
	 * @param avgCut  the value for fos_audit_cp_day.AVG_CUT
	 * @mbggenerated
	 */
	public void setAvgCut(BigDecimal avgCut) {
		this.avgCut = avgCut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.AVG_SALE_REBATE
	 * @return  the value of fos_audit_cp_day.AVG_SALE_REBATE
	 * @mbggenerated
	 */
	public BigDecimal getAvgSaleRebate() {
		return avgSaleRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.AVG_SALE_REBATE
	 * @param avgSaleRebate  the value for fos_audit_cp_day.AVG_SALE_REBATE
	 * @mbggenerated
	 */
	public void setAvgSaleRebate(BigDecimal avgSaleRebate) {
		this.avgSaleRebate = avgSaleRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.AVG_MONEY
	 * @return  the value of fos_audit_cp_day.AVG_MONEY
	 * @mbggenerated
	 */
	public BigDecimal getAvgMoney() {
		return avgMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.AVG_MONEY
	 * @param avgMoney  the value for fos_audit_cp_day.AVG_MONEY
	 * @mbggenerated
	 */
	public void setAvgMoney(BigDecimal avgMoney) {
		this.avgMoney = avgMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.AVG_RETURN_MONEY
	 * @return  the value of fos_audit_cp_day.AVG_RETURN_MONEY
	 * @mbggenerated
	 */
	public BigDecimal getAvgReturnMoney() {
		return avgReturnMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.AVG_RETURN_MONEY
	 * @param avgReturnMoney  the value for fos_audit_cp_day.AVG_RETURN_MONEY
	 * @mbggenerated
	 */
	public void setAvgReturnMoney(BigDecimal avgReturnMoney) {
		this.avgReturnMoney = avgReturnMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.ORDER_MONTH_STATUS
	 * @return  the value of fos_audit_cp_day.ORDER_MONTH_STATUS
	 * @mbggenerated
	 */
	public Byte getOrderMonthStatus() {
		return orderMonthStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.ORDER_MONTH_STATUS
	 * @param orderMonthStatus  the value for fos_audit_cp_day.ORDER_MONTH_STATUS
	 * @mbggenerated
	 */
	public void setOrderMonthStatus(Byte orderMonthStatus) {
		this.orderMonthStatus = orderMonthStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.FINANCIAL_DRAWBILL_STATUS
	 * @return  the value of fos_audit_cp_day.FINANCIAL_DRAWBILL_STATUS
	 * @mbggenerated
	 */
	public Byte getFinancialDrawbillStatus() {
		return financialDrawbillStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.FINANCIAL_DRAWBILL_STATUS
	 * @param financialDrawbillStatus  the value for fos_audit_cp_day.FINANCIAL_DRAWBILL_STATUS
	 * @mbggenerated
	 */
	public void setFinancialDrawbillStatus(Byte financialDrawbillStatus) {
		this.financialDrawbillStatus = financialDrawbillStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fos_audit_cp_day.FINANCIAL_RECEIPT_STATUS
	 * @return  the value of fos_audit_cp_day.FINANCIAL_RECEIPT_STATUS
	 * @mbggenerated
	 */
	public Byte getFinancialReceiptStatus() {
		return financialReceiptStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fos_audit_cp_day.FINANCIAL_RECEIPT_STATUS
	 * @param financialReceiptStatus  the value for fos_audit_cp_day.FINANCIAL_RECEIPT_STATUS
	 * @mbggenerated
	 */
	public void setFinancialReceiptStatus(Byte financialReceiptStatus) {
		this.financialReceiptStatus = financialReceiptStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_cp_day
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", ocDayId=").append(ocDayId);
		sb.append(", orderSubmitConfirm=").append(orderSubmitConfirm);
		sb.append(", cpSubmitPayunit=").append(cpSubmitPayunit);
		sb.append(", cpSubmitOcount=").append(cpSubmitOcount);
		sb.append(", cpSubmitOamount=").append(cpSubmitOamount);
		sb.append(", financialSubmitCpStatus=").append(financialSubmitCpStatus);
		sb.append(", financialSubmitPayunit=").append(financialSubmitPayunit);
		sb.append(", financialSubmitOcount=").append(financialSubmitOcount);
		sb.append(", financialSubmitOamount=").append(financialSubmitOamount);
		sb.append(", financialSubmitCpDate=").append(financialSubmitCpDate);
		sb.append(", financialSubmitCpNotthroughTime=").append(
				financialSubmitCpNotthroughTime);
		sb.append(", financialSubmitCpNotthroughReason=").append(
				financialSubmitCpNotthroughReason);
		sb.append(", avgMonthOcount=").append(avgMonthOcount);
		sb.append(", avgMonthOamount=").append(avgMonthOamount);
		sb.append(", avgCut=").append(avgCut);
		sb.append(", avgSaleRebate=").append(avgSaleRebate);
		sb.append(", avgMoney=").append(avgMoney);
		sb.append(", avgReturnMoney=").append(avgReturnMoney);
		sb.append(", orderMonthStatus=").append(orderMonthStatus);
		sb.append(", financialDrawbillStatus=").append(financialDrawbillStatus);
		sb.append(", financialReceiptStatus=").append(financialReceiptStatus);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}