package com.imopan.adv.platform.entity.fos;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class FosChannelMonthExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	protected Integer limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	protected Integer limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public FosChannelMonthExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public Integer getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public Integer getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdIsNull() {
			addCriterion("CHANNEL_ORDER_ID is null");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdIsNotNull() {
			addCriterion("CHANNEL_ORDER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdEqualTo(Integer value) {
			addCriterion("CHANNEL_ORDER_ID =", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdNotEqualTo(Integer value) {
			addCriterion("CHANNEL_ORDER_ID <>", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdGreaterThan(Integer value) {
			addCriterion("CHANNEL_ORDER_ID >", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("CHANNEL_ORDER_ID >=", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdLessThan(Integer value) {
			addCriterion("CHANNEL_ORDER_ID <", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdLessThanOrEqualTo(Integer value) {
			addCriterion("CHANNEL_ORDER_ID <=", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdIn(List<Integer> values) {
			addCriterion("CHANNEL_ORDER_ID in", values, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdNotIn(List<Integer> values) {
			addCriterion("CHANNEL_ORDER_ID not in", values, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdBetween(Integer value1, Integer value2) {
			addCriterion("CHANNEL_ORDER_ID between", value1, value2, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdNotBetween(Integer value1, Integer value2) {
			addCriterion("CHANNEL_ORDER_ID not between", value1, value2, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("ORDER_ID is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("ORDER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(Integer value) {
			addCriterion("ORDER_ID =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(Integer value) {
			addCriterion("ORDER_ID <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(Integer value) {
			addCriterion("ORDER_ID >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ORDER_ID >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(Integer value) {
			addCriterion("ORDER_ID <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
			addCriterion("ORDER_ID <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<Integer> values) {
			addCriterion("ORDER_ID in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<Integer> values) {
			addCriterion("ORDER_ID not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_ID between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_ID not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderNameIsNull() {
			addCriterion("ORDER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andOrderNameIsNotNull() {
			addCriterion("ORDER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNameEqualTo(String value) {
			addCriterion("ORDER_NAME =", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotEqualTo(String value) {
			addCriterion("ORDER_NAME <>", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameGreaterThan(String value) {
			addCriterion("ORDER_NAME >", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_NAME >=", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameLessThan(String value) {
			addCriterion("ORDER_NAME <", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameLessThanOrEqualTo(String value) {
			addCriterion("ORDER_NAME <=", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameLike(String value) {
			addCriterion("ORDER_NAME like", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotLike(String value) {
			addCriterion("ORDER_NAME not like", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameIn(List<String> values) {
			addCriterion("ORDER_NAME in", values, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotIn(List<String> values) {
			addCriterion("ORDER_NAME not in", values, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameBetween(String value1, String value2) {
			addCriterion("ORDER_NAME between", value1, value2, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotBetween(String value1, String value2) {
			addCriterion("ORDER_NAME not between", value1, value2, "orderName");
			return (Criteria) this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("PRODUCT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("PRODUCT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("PRODUCT_NAME =", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("PRODUCT_NAME <>", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("PRODUCT_NAME >", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME >=", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("PRODUCT_NAME <", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME <=", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("PRODUCT_NAME like", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("PRODUCT_NAME not like", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameIn(List<String> values) {
			addCriterion("PRODUCT_NAME in", values, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotIn(List<String> values) {
			addCriterion("PRODUCT_NAME not in", values, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME between", value1, value2, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME not between", value1, value2, "productName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameIsNull() {
			addCriterion("ORDER_DIRECTOR_NAME is null");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameIsNotNull() {
			addCriterion("ORDER_DIRECTOR_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameEqualTo(String value) {
			addCriterion("ORDER_DIRECTOR_NAME =", value, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameNotEqualTo(String value) {
			addCriterion("ORDER_DIRECTOR_NAME <>", value, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameGreaterThan(String value) {
			addCriterion("ORDER_DIRECTOR_NAME >", value, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_DIRECTOR_NAME >=", value, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameLessThan(String value) {
			addCriterion("ORDER_DIRECTOR_NAME <", value, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameLessThanOrEqualTo(String value) {
			addCriterion("ORDER_DIRECTOR_NAME <=", value, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameLike(String value) {
			addCriterion("ORDER_DIRECTOR_NAME like", value, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameNotLike(String value) {
			addCriterion("ORDER_DIRECTOR_NAME not like", value, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameIn(List<String> values) {
			addCriterion("ORDER_DIRECTOR_NAME in", values, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameNotIn(List<String> values) {
			addCriterion("ORDER_DIRECTOR_NAME not in", values, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameBetween(String value1, String value2) {
			addCriterion("ORDER_DIRECTOR_NAME between", value1, value2, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameNotBetween(String value1, String value2) {
			addCriterion("ORDER_DIRECTOR_NAME not between", value1, value2, "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andCpMainIsNull() {
			addCriterion("CP_MAIN is null");
			return (Criteria) this;
		}

		public Criteria andCpMainIsNotNull() {
			addCriterion("CP_MAIN is not null");
			return (Criteria) this;
		}

		public Criteria andCpMainEqualTo(Byte value) {
			addCriterion("CP_MAIN =", value, "cpMain");
			return (Criteria) this;
		}

		public Criteria andCpMainNotEqualTo(Byte value) {
			addCriterion("CP_MAIN <>", value, "cpMain");
			return (Criteria) this;
		}

		public Criteria andCpMainGreaterThan(Byte value) {
			addCriterion("CP_MAIN >", value, "cpMain");
			return (Criteria) this;
		}

		public Criteria andCpMainGreaterThanOrEqualTo(Byte value) {
			addCriterion("CP_MAIN >=", value, "cpMain");
			return (Criteria) this;
		}

		public Criteria andCpMainLessThan(Byte value) {
			addCriterion("CP_MAIN <", value, "cpMain");
			return (Criteria) this;
		}

		public Criteria andCpMainLessThanOrEqualTo(Byte value) {
			addCriterion("CP_MAIN <=", value, "cpMain");
			return (Criteria) this;
		}

		public Criteria andCpMainIn(List<Byte> values) {
			addCriterion("CP_MAIN in", values, "cpMain");
			return (Criteria) this;
		}

		public Criteria andCpMainNotIn(List<Byte> values) {
			addCriterion("CP_MAIN not in", values, "cpMain");
			return (Criteria) this;
		}

		public Criteria andCpMainBetween(Byte value1, Byte value2) {
			addCriterion("CP_MAIN between", value1, value2, "cpMain");
			return (Criteria) this;
		}

		public Criteria andCpMainNotBetween(Byte value1, Byte value2) {
			addCriterion("CP_MAIN not between", value1, value2, "cpMain");
			return (Criteria) this;
		}

		public Criteria andRelationIdIsNull() {
			addCriterion("RELATION_ID is null");
			return (Criteria) this;
		}

		public Criteria andRelationIdIsNotNull() {
			addCriterion("RELATION_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRelationIdEqualTo(Integer value) {
			addCriterion("RELATION_ID =", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdNotEqualTo(Integer value) {
			addCriterion("RELATION_ID <>", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdGreaterThan(Integer value) {
			addCriterion("RELATION_ID >", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("RELATION_ID >=", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdLessThan(Integer value) {
			addCriterion("RELATION_ID <", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdLessThanOrEqualTo(Integer value) {
			addCriterion("RELATION_ID <=", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdIn(List<Integer> values) {
			addCriterion("RELATION_ID in", values, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdNotIn(List<Integer> values) {
			addCriterion("RELATION_ID not in", values, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdBetween(Integer value1, Integer value2) {
			addCriterion("RELATION_ID between", value1, value2, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdNotBetween(Integer value1, Integer value2) {
			addCriterion("RELATION_ID not between", value1, value2, "relationId");
			return (Criteria) this;
		}

		public Criteria andChannelIdIsNull() {
			addCriterion("CHANNEL_ID is null");
			return (Criteria) this;
		}

		public Criteria andChannelIdIsNotNull() {
			addCriterion("CHANNEL_ID is not null");
			return (Criteria) this;
		}

		public Criteria andChannelIdEqualTo(Integer value) {
			addCriterion("CHANNEL_ID =", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotEqualTo(Integer value) {
			addCriterion("CHANNEL_ID <>", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdGreaterThan(Integer value) {
			addCriterion("CHANNEL_ID >", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("CHANNEL_ID >=", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdLessThan(Integer value) {
			addCriterion("CHANNEL_ID <", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdLessThanOrEqualTo(Integer value) {
			addCriterion("CHANNEL_ID <=", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdIn(List<Integer> values) {
			addCriterion("CHANNEL_ID in", values, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotIn(List<Integer> values) {
			addCriterion("CHANNEL_ID not in", values, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdBetween(Integer value1, Integer value2) {
			addCriterion("CHANNEL_ID between", value1, value2, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotBetween(Integer value1, Integer value2) {
			addCriterion("CHANNEL_ID not between", value1, value2, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelNameIsNull() {
			addCriterion("CHANNEL_NAME is null");
			return (Criteria) this;
		}

		public Criteria andChannelNameIsNotNull() {
			addCriterion("CHANNEL_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andChannelNameEqualTo(String value) {
			addCriterion("CHANNEL_NAME =", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotEqualTo(String value) {
			addCriterion("CHANNEL_NAME <>", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameGreaterThan(String value) {
			addCriterion("CHANNEL_NAME >", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
			addCriterion("CHANNEL_NAME >=", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameLessThan(String value) {
			addCriterion("CHANNEL_NAME <", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameLessThanOrEqualTo(String value) {
			addCriterion("CHANNEL_NAME <=", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameLike(String value) {
			addCriterion("CHANNEL_NAME like", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotLike(String value) {
			addCriterion("CHANNEL_NAME not like", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameIn(List<String> values) {
			addCriterion("CHANNEL_NAME in", values, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotIn(List<String> values) {
			addCriterion("CHANNEL_NAME not in", values, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameBetween(String value1, String value2) {
			addCriterion("CHANNEL_NAME between", value1, value2, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotBetween(String value1, String value2) {
			addCriterion("CHANNEL_NAME not between", value1, value2, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameIsNull() {
			addCriterion("CHANNEL_DIRECTOR_NAME is null");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameIsNotNull() {
			addCriterion("CHANNEL_DIRECTOR_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameEqualTo(String value) {
			addCriterion("CHANNEL_DIRECTOR_NAME =", value, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameNotEqualTo(String value) {
			addCriterion("CHANNEL_DIRECTOR_NAME <>", value, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameGreaterThan(String value) {
			addCriterion("CHANNEL_DIRECTOR_NAME >", value, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameGreaterThanOrEqualTo(String value) {
			addCriterion("CHANNEL_DIRECTOR_NAME >=", value, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameLessThan(String value) {
			addCriterion("CHANNEL_DIRECTOR_NAME <", value, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameLessThanOrEqualTo(String value) {
			addCriterion("CHANNEL_DIRECTOR_NAME <=", value, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameLike(String value) {
			addCriterion("CHANNEL_DIRECTOR_NAME like", value, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameNotLike(String value) {
			addCriterion("CHANNEL_DIRECTOR_NAME not like", value, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameIn(List<String> values) {
			addCriterion("CHANNEL_DIRECTOR_NAME in", values, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameNotIn(List<String> values) {
			addCriterion("CHANNEL_DIRECTOR_NAME not in", values, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameBetween(String value1, String value2) {
			addCriterion("CHANNEL_DIRECTOR_NAME between", value1, value2, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameNotBetween(String value1, String value2) {
			addCriterion("CHANNEL_DIRECTOR_NAME not between", value1, value2, "channelDirectorName");
			return (Criteria) this;
		}

		public Criteria andCUnitIsNull() {
			addCriterion("C_UNIT is null");
			return (Criteria) this;
		}

		public Criteria andCUnitIsNotNull() {
			addCriterion("C_UNIT is not null");
			return (Criteria) this;
		}

		public Criteria andCUnitEqualTo(BigDecimal value) {
			addCriterion("C_UNIT =", value, "cUnit");
			return (Criteria) this;
		}

		public Criteria andCUnitNotEqualTo(BigDecimal value) {
			addCriterion("C_UNIT <>", value, "cUnit");
			return (Criteria) this;
		}

		public Criteria andCUnitGreaterThan(BigDecimal value) {
			addCriterion("C_UNIT >", value, "cUnit");
			return (Criteria) this;
		}

		public Criteria andCUnitGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("C_UNIT >=", value, "cUnit");
			return (Criteria) this;
		}

		public Criteria andCUnitLessThan(BigDecimal value) {
			addCriterion("C_UNIT <", value, "cUnit");
			return (Criteria) this;
		}

		public Criteria andCUnitLessThanOrEqualTo(BigDecimal value) {
			addCriterion("C_UNIT <=", value, "cUnit");
			return (Criteria) this;
		}

		public Criteria andCUnitIn(List<BigDecimal> values) {
			addCriterion("C_UNIT in", values, "cUnit");
			return (Criteria) this;
		}

		public Criteria andCUnitNotIn(List<BigDecimal> values) {
			addCriterion("C_UNIT not in", values, "cUnit");
			return (Criteria) this;
		}

		public Criteria andCUnitBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("C_UNIT between", value1, value2, "cUnit");
			return (Criteria) this;
		}

		public Criteria andCUnitNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("C_UNIT not between", value1, value2, "cUnit");
			return (Criteria) this;
		}

		public Criteria andCCountIsNull() {
			addCriterion("C_COUNT is null");
			return (Criteria) this;
		}

		public Criteria andCCountIsNotNull() {
			addCriterion("C_COUNT is not null");
			return (Criteria) this;
		}

		public Criteria andCCountEqualTo(Integer value) {
			addCriterion("C_COUNT =", value, "cCount");
			return (Criteria) this;
		}

		public Criteria andCCountNotEqualTo(Integer value) {
			addCriterion("C_COUNT <>", value, "cCount");
			return (Criteria) this;
		}

		public Criteria andCCountGreaterThan(Integer value) {
			addCriterion("C_COUNT >", value, "cCount");
			return (Criteria) this;
		}

		public Criteria andCCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("C_COUNT >=", value, "cCount");
			return (Criteria) this;
		}

		public Criteria andCCountLessThan(Integer value) {
			addCriterion("C_COUNT <", value, "cCount");
			return (Criteria) this;
		}

		public Criteria andCCountLessThanOrEqualTo(Integer value) {
			addCriterion("C_COUNT <=", value, "cCount");
			return (Criteria) this;
		}

		public Criteria andCCountIn(List<Integer> values) {
			addCriterion("C_COUNT in", values, "cCount");
			return (Criteria) this;
		}

		public Criteria andCCountNotIn(List<Integer> values) {
			addCriterion("C_COUNT not in", values, "cCount");
			return (Criteria) this;
		}

		public Criteria andCCountBetween(Integer value1, Integer value2) {
			addCriterion("C_COUNT between", value1, value2, "cCount");
			return (Criteria) this;
		}

		public Criteria andCCountNotBetween(Integer value1, Integer value2) {
			addCriterion("C_COUNT not between", value1, value2, "cCount");
			return (Criteria) this;
		}

		public Criteria andCAmountIsNull() {
			addCriterion("C_AMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andCAmountIsNotNull() {
			addCriterion("C_AMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andCAmountEqualTo(BigDecimal value) {
			addCriterion("C_AMOUNT =", value, "cAmount");
			return (Criteria) this;
		}

		public Criteria andCAmountNotEqualTo(BigDecimal value) {
			addCriterion("C_AMOUNT <>", value, "cAmount");
			return (Criteria) this;
		}

		public Criteria andCAmountGreaterThan(BigDecimal value) {
			addCriterion("C_AMOUNT >", value, "cAmount");
			return (Criteria) this;
		}

		public Criteria andCAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("C_AMOUNT >=", value, "cAmount");
			return (Criteria) this;
		}

		public Criteria andCAmountLessThan(BigDecimal value) {
			addCriterion("C_AMOUNT <", value, "cAmount");
			return (Criteria) this;
		}

		public Criteria andCAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("C_AMOUNT <=", value, "cAmount");
			return (Criteria) this;
		}

		public Criteria andCAmountIn(List<BigDecimal> values) {
			addCriterion("C_AMOUNT in", values, "cAmount");
			return (Criteria) this;
		}

		public Criteria andCAmountNotIn(List<BigDecimal> values) {
			addCriterion("C_AMOUNT not in", values, "cAmount");
			return (Criteria) this;
		}

		public Criteria andCAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("C_AMOUNT between", value1, value2, "cAmount");
			return (Criteria) this;
		}

		public Criteria andCAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("C_AMOUNT not between", value1, value2, "cAmount");
			return (Criteria) this;
		}

		public Criteria andSubAmountIsNull() {
			addCriterion("SUB_AMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andSubAmountIsNotNull() {
			addCriterion("SUB_AMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andSubAmountEqualTo(BigDecimal value) {
			addCriterion("SUB_AMOUNT =", value, "subAmount");
			return (Criteria) this;
		}

		public Criteria andSubAmountNotEqualTo(BigDecimal value) {
			addCriterion("SUB_AMOUNT <>", value, "subAmount");
			return (Criteria) this;
		}

		public Criteria andSubAmountGreaterThan(BigDecimal value) {
			addCriterion("SUB_AMOUNT >", value, "subAmount");
			return (Criteria) this;
		}

		public Criteria andSubAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("SUB_AMOUNT >=", value, "subAmount");
			return (Criteria) this;
		}

		public Criteria andSubAmountLessThan(BigDecimal value) {
			addCriterion("SUB_AMOUNT <", value, "subAmount");
			return (Criteria) this;
		}

		public Criteria andSubAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("SUB_AMOUNT <=", value, "subAmount");
			return (Criteria) this;
		}

		public Criteria andSubAmountIn(List<BigDecimal> values) {
			addCriterion("SUB_AMOUNT in", values, "subAmount");
			return (Criteria) this;
		}

		public Criteria andSubAmountNotIn(List<BigDecimal> values) {
			addCriterion("SUB_AMOUNT not in", values, "subAmount");
			return (Criteria) this;
		}

		public Criteria andSubAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("SUB_AMOUNT between", value1, value2, "subAmount");
			return (Criteria) this;
		}

		public Criteria andSubAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("SUB_AMOUNT not between", value1, value2, "subAmount");
			return (Criteria) this;
		}

		public Criteria andCCountSumIsNull() {
			addCriterion("C_COUNT_SUM is null");
			return (Criteria) this;
		}

		public Criteria andCCountSumIsNotNull() {
			addCriterion("C_COUNT_SUM is not null");
			return (Criteria) this;
		}

		public Criteria andCCountSumEqualTo(Integer value) {
			addCriterion("C_COUNT_SUM =", value, "cCountSum");
			return (Criteria) this;
		}

		public Criteria andCCountSumNotEqualTo(Integer value) {
			addCriterion("C_COUNT_SUM <>", value, "cCountSum");
			return (Criteria) this;
		}

		public Criteria andCCountSumGreaterThan(Integer value) {
			addCriterion("C_COUNT_SUM >", value, "cCountSum");
			return (Criteria) this;
		}

		public Criteria andCCountSumGreaterThanOrEqualTo(Integer value) {
			addCriterion("C_COUNT_SUM >=", value, "cCountSum");
			return (Criteria) this;
		}

		public Criteria andCCountSumLessThan(Integer value) {
			addCriterion("C_COUNT_SUM <", value, "cCountSum");
			return (Criteria) this;
		}

		public Criteria andCCountSumLessThanOrEqualTo(Integer value) {
			addCriterion("C_COUNT_SUM <=", value, "cCountSum");
			return (Criteria) this;
		}

		public Criteria andCCountSumIn(List<Integer> values) {
			addCriterion("C_COUNT_SUM in", values, "cCountSum");
			return (Criteria) this;
		}

		public Criteria andCCountSumNotIn(List<Integer> values) {
			addCriterion("C_COUNT_SUM not in", values, "cCountSum");
			return (Criteria) this;
		}

		public Criteria andCCountSumBetween(Integer value1, Integer value2) {
			addCriterion("C_COUNT_SUM between", value1, value2, "cCountSum");
			return (Criteria) this;
		}

		public Criteria andCCountSumNotBetween(Integer value1, Integer value2) {
			addCriterion("C_COUNT_SUM not between", value1, value2, "cCountSum");
			return (Criteria) this;
		}

		public Criteria andCAmountSumIsNull() {
			addCriterion("C_AMOUNT_SUM is null");
			return (Criteria) this;
		}

		public Criteria andCAmountSumIsNotNull() {
			addCriterion("C_AMOUNT_SUM is not null");
			return (Criteria) this;
		}

		public Criteria andCAmountSumEqualTo(BigDecimal value) {
			addCriterion("C_AMOUNT_SUM =", value, "cAmountSum");
			return (Criteria) this;
		}

		public Criteria andCAmountSumNotEqualTo(BigDecimal value) {
			addCriterion("C_AMOUNT_SUM <>", value, "cAmountSum");
			return (Criteria) this;
		}

		public Criteria andCAmountSumGreaterThan(BigDecimal value) {
			addCriterion("C_AMOUNT_SUM >", value, "cAmountSum");
			return (Criteria) this;
		}

		public Criteria andCAmountSumGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("C_AMOUNT_SUM >=", value, "cAmountSum");
			return (Criteria) this;
		}

		public Criteria andCAmountSumLessThan(BigDecimal value) {
			addCriterion("C_AMOUNT_SUM <", value, "cAmountSum");
			return (Criteria) this;
		}

		public Criteria andCAmountSumLessThanOrEqualTo(BigDecimal value) {
			addCriterion("C_AMOUNT_SUM <=", value, "cAmountSum");
			return (Criteria) this;
		}

		public Criteria andCAmountSumIn(List<BigDecimal> values) {
			addCriterion("C_AMOUNT_SUM in", values, "cAmountSum");
			return (Criteria) this;
		}

		public Criteria andCAmountSumNotIn(List<BigDecimal> values) {
			addCriterion("C_AMOUNT_SUM not in", values, "cAmountSum");
			return (Criteria) this;
		}

		public Criteria andCAmountSumBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("C_AMOUNT_SUM between", value1, value2, "cAmountSum");
			return (Criteria) this;
		}

		public Criteria andCAmountSumNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("C_AMOUNT_SUM not between", value1, value2, "cAmountSum");
			return (Criteria) this;
		}

		public Criteria andMediaRebateIsNull() {
			addCriterion("MEDIA_REBATE is null");
			return (Criteria) this;
		}

		public Criteria andMediaRebateIsNotNull() {
			addCriterion("MEDIA_REBATE is not null");
			return (Criteria) this;
		}

		public Criteria andMediaRebateEqualTo(BigDecimal value) {
			addCriterion("MEDIA_REBATE =", value, "mediaRebate");
			return (Criteria) this;
		}

		public Criteria andMediaRebateNotEqualTo(BigDecimal value) {
			addCriterion("MEDIA_REBATE <>", value, "mediaRebate");
			return (Criteria) this;
		}

		public Criteria andMediaRebateGreaterThan(BigDecimal value) {
			addCriterion("MEDIA_REBATE >", value, "mediaRebate");
			return (Criteria) this;
		}

		public Criteria andMediaRebateGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("MEDIA_REBATE >=", value, "mediaRebate");
			return (Criteria) this;
		}

		public Criteria andMediaRebateLessThan(BigDecimal value) {
			addCriterion("MEDIA_REBATE <", value, "mediaRebate");
			return (Criteria) this;
		}

		public Criteria andMediaRebateLessThanOrEqualTo(BigDecimal value) {
			addCriterion("MEDIA_REBATE <=", value, "mediaRebate");
			return (Criteria) this;
		}

		public Criteria andMediaRebateIn(List<BigDecimal> values) {
			addCriterion("MEDIA_REBATE in", values, "mediaRebate");
			return (Criteria) this;
		}

		public Criteria andMediaRebateNotIn(List<BigDecimal> values) {
			addCriterion("MEDIA_REBATE not in", values, "mediaRebate");
			return (Criteria) this;
		}

		public Criteria andMediaRebateBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("MEDIA_REBATE between", value1, value2, "mediaRebate");
			return (Criteria) this;
		}

		public Criteria andMediaRebateNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("MEDIA_REBATE not between", value1, value2, "mediaRebate");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseIsNull() {
			addCriterion("OTHER_EXPENSE is null");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseIsNotNull() {
			addCriterion("OTHER_EXPENSE is not null");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseEqualTo(BigDecimal value) {
			addCriterion("OTHER_EXPENSE =", value, "otherExpense");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseNotEqualTo(BigDecimal value) {
			addCriterion("OTHER_EXPENSE <>", value, "otherExpense");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseGreaterThan(BigDecimal value) {
			addCriterion("OTHER_EXPENSE >", value, "otherExpense");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("OTHER_EXPENSE >=", value, "otherExpense");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseLessThan(BigDecimal value) {
			addCriterion("OTHER_EXPENSE <", value, "otherExpense");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseLessThanOrEqualTo(BigDecimal value) {
			addCriterion("OTHER_EXPENSE <=", value, "otherExpense");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseIn(List<BigDecimal> values) {
			addCriterion("OTHER_EXPENSE in", values, "otherExpense");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseNotIn(List<BigDecimal> values) {
			addCriterion("OTHER_EXPENSE not in", values, "otherExpense");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("OTHER_EXPENSE between", value1, value2, "otherExpense");
			return (Criteria) this;
		}

		public Criteria andOtherExpenseNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("OTHER_EXPENSE not between", value1, value2, "otherExpense");
			return (Criteria) this;
		}

		public Criteria andChannelCutIsNull() {
			addCriterion("CHANNEL_CUT is null");
			return (Criteria) this;
		}

		public Criteria andChannelCutIsNotNull() {
			addCriterion("CHANNEL_CUT is not null");
			return (Criteria) this;
		}

		public Criteria andChannelCutEqualTo(BigDecimal value) {
			addCriterion("CHANNEL_CUT =", value, "channelCut");
			return (Criteria) this;
		}

		public Criteria andChannelCutNotEqualTo(BigDecimal value) {
			addCriterion("CHANNEL_CUT <>", value, "channelCut");
			return (Criteria) this;
		}

		public Criteria andChannelCutGreaterThan(BigDecimal value) {
			addCriterion("CHANNEL_CUT >", value, "channelCut");
			return (Criteria) this;
		}

		public Criteria andChannelCutGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("CHANNEL_CUT >=", value, "channelCut");
			return (Criteria) this;
		}

		public Criteria andChannelCutLessThan(BigDecimal value) {
			addCriterion("CHANNEL_CUT <", value, "channelCut");
			return (Criteria) this;
		}

		public Criteria andChannelCutLessThanOrEqualTo(BigDecimal value) {
			addCriterion("CHANNEL_CUT <=", value, "channelCut");
			return (Criteria) this;
		}

		public Criteria andChannelCutIn(List<BigDecimal> values) {
			addCriterion("CHANNEL_CUT in", values, "channelCut");
			return (Criteria) this;
		}

		public Criteria andChannelCutNotIn(List<BigDecimal> values) {
			addCriterion("CHANNEL_CUT not in", values, "channelCut");
			return (Criteria) this;
		}

		public Criteria andChannelCutBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("CHANNEL_CUT between", value1, value2, "channelCut");
			return (Criteria) this;
		}

		public Criteria andChannelCutNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("CHANNEL_CUT not between", value1, value2, "channelCut");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusIsNull() {
			addCriterion("ENTRY_MONTH_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusIsNotNull() {
			addCriterion("ENTRY_MONTH_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusEqualTo(Byte value) {
			addCriterion("ENTRY_MONTH_STATUS =", value, "entryMonthStatus");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusNotEqualTo(Byte value) {
			addCriterion("ENTRY_MONTH_STATUS <>", value, "entryMonthStatus");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusGreaterThan(Byte value) {
			addCriterion("ENTRY_MONTH_STATUS >", value, "entryMonthStatus");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("ENTRY_MONTH_STATUS >=", value, "entryMonthStatus");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusLessThan(Byte value) {
			addCriterion("ENTRY_MONTH_STATUS <", value, "entryMonthStatus");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusLessThanOrEqualTo(Byte value) {
			addCriterion("ENTRY_MONTH_STATUS <=", value, "entryMonthStatus");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusIn(List<Byte> values) {
			addCriterion("ENTRY_MONTH_STATUS in", values, "entryMonthStatus");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusNotIn(List<Byte> values) {
			addCriterion("ENTRY_MONTH_STATUS not in", values, "entryMonthStatus");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusBetween(Byte value1, Byte value2) {
			addCriterion("ENTRY_MONTH_STATUS between", value1, value2, "entryMonthStatus");
			return (Criteria) this;
		}

		public Criteria andEntryMonthStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("ENTRY_MONTH_STATUS not between", value1, value2, "entryMonthStatus");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyIsNull() {
			addCriterion("ENTRY_MONEY is null");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyIsNotNull() {
			addCriterion("ENTRY_MONEY is not null");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyEqualTo(Byte value) {
			addCriterion("ENTRY_MONEY =", value, "entryMoney");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyNotEqualTo(Byte value) {
			addCriterion("ENTRY_MONEY <>", value, "entryMoney");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyGreaterThan(Byte value) {
			addCriterion("ENTRY_MONEY >", value, "entryMoney");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyGreaterThanOrEqualTo(Byte value) {
			addCriterion("ENTRY_MONEY >=", value, "entryMoney");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyLessThan(Byte value) {
			addCriterion("ENTRY_MONEY <", value, "entryMoney");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyLessThanOrEqualTo(Byte value) {
			addCriterion("ENTRY_MONEY <=", value, "entryMoney");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyIn(List<Byte> values) {
			addCriterion("ENTRY_MONEY in", values, "entryMoney");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyNotIn(List<Byte> values) {
			addCriterion("ENTRY_MONEY not in", values, "entryMoney");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyBetween(Byte value1, Byte value2) {
			addCriterion("ENTRY_MONEY between", value1, value2, "entryMoney");
			return (Criteria) this;
		}

		public Criteria andEntryMoneyNotBetween(Byte value1, Byte value2) {
			addCriterion("ENTRY_MONEY not between", value1, value2, "entryMoney");
			return (Criteria) this;
		}

		public Criteria andEntryTicketIsNull() {
			addCriterion("ENTRY_TICKET is null");
			return (Criteria) this;
		}

		public Criteria andEntryTicketIsNotNull() {
			addCriterion("ENTRY_TICKET is not null");
			return (Criteria) this;
		}

		public Criteria andEntryTicketEqualTo(Byte value) {
			addCriterion("ENTRY_TICKET =", value, "entryTicket");
			return (Criteria) this;
		}

		public Criteria andEntryTicketNotEqualTo(Byte value) {
			addCriterion("ENTRY_TICKET <>", value, "entryTicket");
			return (Criteria) this;
		}

		public Criteria andEntryTicketGreaterThan(Byte value) {
			addCriterion("ENTRY_TICKET >", value, "entryTicket");
			return (Criteria) this;
		}

		public Criteria andEntryTicketGreaterThanOrEqualTo(Byte value) {
			addCriterion("ENTRY_TICKET >=", value, "entryTicket");
			return (Criteria) this;
		}

		public Criteria andEntryTicketLessThan(Byte value) {
			addCriterion("ENTRY_TICKET <", value, "entryTicket");
			return (Criteria) this;
		}

		public Criteria andEntryTicketLessThanOrEqualTo(Byte value) {
			addCriterion("ENTRY_TICKET <=", value, "entryTicket");
			return (Criteria) this;
		}

		public Criteria andEntryTicketIn(List<Byte> values) {
			addCriterion("ENTRY_TICKET in", values, "entryTicket");
			return (Criteria) this;
		}

		public Criteria andEntryTicketNotIn(List<Byte> values) {
			addCriterion("ENTRY_TICKET not in", values, "entryTicket");
			return (Criteria) this;
		}

		public Criteria andEntryTicketBetween(Byte value1, Byte value2) {
			addCriterion("ENTRY_TICKET between", value1, value2, "entryTicket");
			return (Criteria) this;
		}

		public Criteria andEntryTicketNotBetween(Byte value1, Byte value2) {
			addCriterion("ENTRY_TICKET not between", value1, value2, "entryTicket");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeIsNull() {
			addCriterion("ENTRY_BEGINTIME is null");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeIsNotNull() {
			addCriterion("ENTRY_BEGINTIME is not null");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeEqualTo(Date value) {
			addCriterionForJDBCDate("ENTRY_BEGINTIME =", value, "entryBegintime");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("ENTRY_BEGINTIME <>", value, "entryBegintime");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeGreaterThan(Date value) {
			addCriterionForJDBCDate("ENTRY_BEGINTIME >", value, "entryBegintime");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ENTRY_BEGINTIME >=", value, "entryBegintime");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeLessThan(Date value) {
			addCriterionForJDBCDate("ENTRY_BEGINTIME <", value, "entryBegintime");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ENTRY_BEGINTIME <=", value, "entryBegintime");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeIn(List<Date> values) {
			addCriterionForJDBCDate("ENTRY_BEGINTIME in", values, "entryBegintime");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("ENTRY_BEGINTIME not in", values, "entryBegintime");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ENTRY_BEGINTIME between", value1, value2, "entryBegintime");
			return (Criteria) this;
		}

		public Criteria andEntryBegintimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ENTRY_BEGINTIME not between", value1, value2, "entryBegintime");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeIsNull() {
			addCriterion("ENTRY_ENDTIME is null");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeIsNotNull() {
			addCriterion("ENTRY_ENDTIME is not null");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeEqualTo(Date value) {
			addCriterionForJDBCDate("ENTRY_ENDTIME =", value, "entryEndtime");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("ENTRY_ENDTIME <>", value, "entryEndtime");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeGreaterThan(Date value) {
			addCriterionForJDBCDate("ENTRY_ENDTIME >", value, "entryEndtime");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ENTRY_ENDTIME >=", value, "entryEndtime");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeLessThan(Date value) {
			addCriterionForJDBCDate("ENTRY_ENDTIME <", value, "entryEndtime");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ENTRY_ENDTIME <=", value, "entryEndtime");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeIn(List<Date> values) {
			addCriterionForJDBCDate("ENTRY_ENDTIME in", values, "entryEndtime");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("ENTRY_ENDTIME not in", values, "entryEndtime");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ENTRY_ENDTIME between", value1, value2, "entryEndtime");
			return (Criteria) this;
		}

		public Criteria andEntryEndtimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ENTRY_ENDTIME not between", value1, value2, "entryEndtime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("`STATUS` is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("`STATUS` is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("`STATUS` =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("`STATUS` <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("`STATUS` >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("`STATUS` >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("`STATUS` <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("`STATUS` <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("`STATUS` in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("`STATUS` not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("`STATUS` between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("`STATUS` not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReceiveIdIsNull() {
			addCriterion("RECEIVE_ID is null");
			return (Criteria) this;
		}

		public Criteria andReceiveIdIsNotNull() {
			addCriterion("RECEIVE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andReceiveIdEqualTo(Integer value) {
			addCriterion("RECEIVE_ID =", value, "receiveId");
			return (Criteria) this;
		}

		public Criteria andReceiveIdNotEqualTo(Integer value) {
			addCriterion("RECEIVE_ID <>", value, "receiveId");
			return (Criteria) this;
		}

		public Criteria andReceiveIdGreaterThan(Integer value) {
			addCriterion("RECEIVE_ID >", value, "receiveId");
			return (Criteria) this;
		}

		public Criteria andReceiveIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("RECEIVE_ID >=", value, "receiveId");
			return (Criteria) this;
		}

		public Criteria andReceiveIdLessThan(Integer value) {
			addCriterion("RECEIVE_ID <", value, "receiveId");
			return (Criteria) this;
		}

		public Criteria andReceiveIdLessThanOrEqualTo(Integer value) {
			addCriterion("RECEIVE_ID <=", value, "receiveId");
			return (Criteria) this;
		}

		public Criteria andReceiveIdIn(List<Integer> values) {
			addCriterion("RECEIVE_ID in", values, "receiveId");
			return (Criteria) this;
		}

		public Criteria andReceiveIdNotIn(List<Integer> values) {
			addCriterion("RECEIVE_ID not in", values, "receiveId");
			return (Criteria) this;
		}

		public Criteria andReceiveIdBetween(Integer value1, Integer value2) {
			addCriterion("RECEIVE_ID between", value1, value2, "receiveId");
			return (Criteria) this;
		}

		public Criteria andReceiveIdNotBetween(Integer value1, Integer value2) {
			addCriterion("RECEIVE_ID not between", value1, value2, "receiveId");
			return (Criteria) this;
		}

		public Criteria andOrderNameLikeInsensitive(String value) {
			addCriterion("upper(ORDER_NAME) like", value.toUpperCase(), "orderName");
			return (Criteria) this;
		}

		public Criteria andProductNameLikeInsensitive(String value) {
			addCriterion("upper(PRODUCT_NAME) like", value.toUpperCase(), "productName");
			return (Criteria) this;
		}

		public Criteria andOrderDirectorNameLikeInsensitive(String value) {
			addCriterion("upper(ORDER_DIRECTOR_NAME) like", value.toUpperCase(), "orderDirectorName");
			return (Criteria) this;
		}

		public Criteria andChannelNameLikeInsensitive(String value) {
			addCriterion("upper(CHANNEL_NAME) like", value.toUpperCase(), "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelDirectorNameLikeInsensitive(String value) {
			addCriterion("upper(CHANNEL_DIRECTOR_NAME) like", value.toUpperCase(), "channelDirectorName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fos_channel_month
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}