package com.imopan.adv.platform.entity.fos;

import com.imopan.adv.platform.common.BaseBean;
import java.io.Serializable;
import java.math.BigDecimal;

public class FosHistory extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.DIRECTOR_COOPERATE_PRODUCT
     *
     * @mbggenerated
     */
    private String directorCooperateProduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.TIME
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.UNIT
     *
     * @mbggenerated
     */
    private BigDecimal unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.CLICK
     *
     * @mbggenerated
     */
    private Integer click;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.SHOULD_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal shouldAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.CP_COUNT
     *
     * @mbggenerated
     */
    private Integer cpCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.DRAW_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal drawAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.CUT
     *
     * @mbggenerated
     */
    private BigDecimal cut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.EXPEND
     *
     * @mbggenerated
     */
    private BigDecimal expend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.ACTUAL_EXPEND
     *
     * @mbggenerated
     */
    private BigDecimal actualExpend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.PROFIT
     *
     * @mbggenerated
     */
    private String profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fos_history.PROFIT_MARGIN
     *
     * @mbggenerated
     */
    private String profitMargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fos_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.ID
     *
     * @return the value of fos_history.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.ID
     *
     * @param id the value for fos_history.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.DIRECTOR_COOPERATE_PRODUCT
     *
     * @return the value of fos_history.DIRECTOR_COOPERATE_PRODUCT
     *
     * @mbggenerated
     */
    public String getDirectorCooperateProduct() {
        return directorCooperateProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.DIRECTOR_COOPERATE_PRODUCT
     *
     * @param directorCooperateProduct the value for fos_history.DIRECTOR_COOPERATE_PRODUCT
     *
     * @mbggenerated
     */
    public void setDirectorCooperateProduct(String directorCooperateProduct) {
        this.directorCooperateProduct = directorCooperateProduct == null ? null : directorCooperateProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.TIME
     *
     * @return the value of fos_history.TIME
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.TIME
     *
     * @param time the value for fos_history.TIME
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.UNIT
     *
     * @return the value of fos_history.UNIT
     *
     * @mbggenerated
     */
    public BigDecimal getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.UNIT
     *
     * @param unit the value for fos_history.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(BigDecimal unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.CLICK
     *
     * @return the value of fos_history.CLICK
     *
     * @mbggenerated
     */
    public Integer getClick() {
        return click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.CLICK
     *
     * @param click the value for fos_history.CLICK
     *
     * @mbggenerated
     */
    public void setClick(Integer click) {
        this.click = click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.SHOULD_AMOUNT
     *
     * @return the value of fos_history.SHOULD_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getShouldAmount() {
        return shouldAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.SHOULD_AMOUNT
     *
     * @param shouldAmount the value for fos_history.SHOULD_AMOUNT
     *
     * @mbggenerated
     */
    public void setShouldAmount(BigDecimal shouldAmount) {
        this.shouldAmount = shouldAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.CP_COUNT
     *
     * @return the value of fos_history.CP_COUNT
     *
     * @mbggenerated
     */
    public Integer getCpCount() {
        return cpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.CP_COUNT
     *
     * @param cpCount the value for fos_history.CP_COUNT
     *
     * @mbggenerated
     */
    public void setCpCount(Integer cpCount) {
        this.cpCount = cpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.DRAW_AMOUNT
     *
     * @return the value of fos_history.DRAW_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getDrawAmount() {
        return drawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.DRAW_AMOUNT
     *
     * @param drawAmount the value for fos_history.DRAW_AMOUNT
     *
     * @mbggenerated
     */
    public void setDrawAmount(BigDecimal drawAmount) {
        this.drawAmount = drawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.CUT
     *
     * @return the value of fos_history.CUT
     *
     * @mbggenerated
     */
    public BigDecimal getCut() {
        return cut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.CUT
     *
     * @param cut the value for fos_history.CUT
     *
     * @mbggenerated
     */
    public void setCut(BigDecimal cut) {
        this.cut = cut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.EXPEND
     *
     * @return the value of fos_history.EXPEND
     *
     * @mbggenerated
     */
    public BigDecimal getExpend() {
        return expend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.EXPEND
     *
     * @param expend the value for fos_history.EXPEND
     *
     * @mbggenerated
     */
    public void setExpend(BigDecimal expend) {
        this.expend = expend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.ACTUAL_EXPEND
     *
     * @return the value of fos_history.ACTUAL_EXPEND
     *
     * @mbggenerated
     */
    public BigDecimal getActualExpend() {
        return actualExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.ACTUAL_EXPEND
     *
     * @param actualExpend the value for fos_history.ACTUAL_EXPEND
     *
     * @mbggenerated
     */
    public void setActualExpend(BigDecimal actualExpend) {
        this.actualExpend = actualExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.PROFIT
     *
     * @return the value of fos_history.PROFIT
     *
     * @mbggenerated
     */
    public String getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.PROFIT
     *
     * @param profit the value for fos_history.PROFIT
     *
     * @mbggenerated
     */
    public void setProfit(String profit) {
        this.profit = profit == null ? null : profit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fos_history.PROFIT_MARGIN
     *
     * @return the value of fos_history.PROFIT_MARGIN
     *
     * @mbggenerated
     */
    public String getProfitMargin() {
        return profitMargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fos_history.PROFIT_MARGIN
     *
     * @param profitMargin the value for fos_history.PROFIT_MARGIN
     *
     * @mbggenerated
     */
    public void setProfitMargin(String profitMargin) {
        this.profitMargin = profitMargin == null ? null : profitMargin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fos_history
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", directorCooperateProduct=").append(directorCooperateProduct);
        sb.append(", time=").append(time);
        sb.append(", unit=").append(unit);
        sb.append(", click=").append(click);
        sb.append(", shouldAmount=").append(shouldAmount);
        sb.append(", cpCount=").append(cpCount);
        sb.append(", drawAmount=").append(drawAmount);
        sb.append(", cut=").append(cut);
        sb.append(", expend=").append(expend);
        sb.append(", actualExpend=").append(actualExpend);
        sb.append(", profit=").append(profit);
        sb.append(", profitMargin=").append(profitMargin);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}