package com.imopan.adv.platform.entity.fos;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class FosIncomeCostExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	protected Integer limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	protected Integer limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public FosIncomeCostExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public Integer getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public Integer getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdIsNull() {
			addCriterion("CHANNEL_ORDER_ID is null");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdIsNotNull() {
			addCriterion("CHANNEL_ORDER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdEqualTo(Integer value) {
			addCriterion("CHANNEL_ORDER_ID =", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdNotEqualTo(Integer value) {
			addCriterion("CHANNEL_ORDER_ID <>", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdGreaterThan(Integer value) {
			addCriterion("CHANNEL_ORDER_ID >", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("CHANNEL_ORDER_ID >=", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdLessThan(Integer value) {
			addCriterion("CHANNEL_ORDER_ID <", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdLessThanOrEqualTo(Integer value) {
			addCriterion("CHANNEL_ORDER_ID <=", value, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdIn(List<Integer> values) {
			addCriterion("CHANNEL_ORDER_ID in", values, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdNotIn(List<Integer> values) {
			addCriterion("CHANNEL_ORDER_ID not in", values, "channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdBetween(Integer value1, Integer value2) {
			addCriterion("CHANNEL_ORDER_ID between", value1, value2,
					"channelOrderId");
			return (Criteria) this;
		}

		public Criteria andChannelOrderIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("CHANNEL_ORDER_ID not between", value1, value2,
					"channelOrderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("ORDER_ID is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("ORDER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(Integer value) {
			addCriterion("ORDER_ID =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(Integer value) {
			addCriterion("ORDER_ID <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(Integer value) {
			addCriterion("ORDER_ID >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ORDER_ID >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(Integer value) {
			addCriterion("ORDER_ID <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
			addCriterion("ORDER_ID <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<Integer> values) {
			addCriterion("ORDER_ID in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<Integer> values) {
			addCriterion("ORDER_ID not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_ID between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_ID not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderNameIsNull() {
			addCriterion("ORDER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andOrderNameIsNotNull() {
			addCriterion("ORDER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNameEqualTo(String value) {
			addCriterion("ORDER_NAME =", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotEqualTo(String value) {
			addCriterion("ORDER_NAME <>", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameGreaterThan(String value) {
			addCriterion("ORDER_NAME >", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_NAME >=", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameLessThan(String value) {
			addCriterion("ORDER_NAME <", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameLessThanOrEqualTo(String value) {
			addCriterion("ORDER_NAME <=", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameLike(String value) {
			addCriterion("ORDER_NAME like", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotLike(String value) {
			addCriterion("ORDER_NAME not like", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameIn(List<String> values) {
			addCriterion("ORDER_NAME in", values, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotIn(List<String> values) {
			addCriterion("ORDER_NAME not in", values, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameBetween(String value1, String value2) {
			addCriterion("ORDER_NAME between", value1, value2, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotBetween(String value1, String value2) {
			addCriterion("ORDER_NAME not between", value1, value2, "orderName");
			return (Criteria) this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("PRODUCT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("PRODUCT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("PRODUCT_NAME =", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("PRODUCT_NAME <>", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("PRODUCT_NAME >", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME >=", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("PRODUCT_NAME <", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME <=", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("PRODUCT_NAME like", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("PRODUCT_NAME not like", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameIn(List<String> values) {
			addCriterion("PRODUCT_NAME in", values, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotIn(List<String> values) {
			addCriterion("PRODUCT_NAME not in", values, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME between", value1, value2, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME not between", value1, value2,
					"productName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameIsNull() {
			addCriterion("COOPERATE_NAME is null");
			return (Criteria) this;
		}

		public Criteria andCooperateNameIsNotNull() {
			addCriterion("COOPERATE_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andCooperateNameEqualTo(String value) {
			addCriterion("COOPERATE_NAME =", value, "cooperateName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameNotEqualTo(String value) {
			addCriterion("COOPERATE_NAME <>", value, "cooperateName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameGreaterThan(String value) {
			addCriterion("COOPERATE_NAME >", value, "cooperateName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameGreaterThanOrEqualTo(String value) {
			addCriterion("COOPERATE_NAME >=", value, "cooperateName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameLessThan(String value) {
			addCriterion("COOPERATE_NAME <", value, "cooperateName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameLessThanOrEqualTo(String value) {
			addCriterion("COOPERATE_NAME <=", value, "cooperateName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameLike(String value) {
			addCriterion("COOPERATE_NAME like", value, "cooperateName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameNotLike(String value) {
			addCriterion("COOPERATE_NAME not like", value, "cooperateName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameIn(List<String> values) {
			addCriterion("COOPERATE_NAME in", values, "cooperateName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameNotIn(List<String> values) {
			addCriterion("COOPERATE_NAME not in", values, "cooperateName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameBetween(String value1, String value2) {
			addCriterion("COOPERATE_NAME between", value1, value2,
					"cooperateName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameNotBetween(String value1, String value2) {
			addCriterion("COOPERATE_NAME not between", value1, value2,
					"cooperateName");
			return (Criteria) this;
		}

		public Criteria andExtendTypeIsNull() {
			addCriterion("EXTEND_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andExtendTypeIsNotNull() {
			addCriterion("EXTEND_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andExtendTypeEqualTo(Byte value) {
			addCriterion("EXTEND_TYPE =", value, "extendType");
			return (Criteria) this;
		}

		public Criteria andExtendTypeNotEqualTo(Byte value) {
			addCriterion("EXTEND_TYPE <>", value, "extendType");
			return (Criteria) this;
		}

		public Criteria andExtendTypeGreaterThan(Byte value) {
			addCriterion("EXTEND_TYPE >", value, "extendType");
			return (Criteria) this;
		}

		public Criteria andExtendTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("EXTEND_TYPE >=", value, "extendType");
			return (Criteria) this;
		}

		public Criteria andExtendTypeLessThan(Byte value) {
			addCriterion("EXTEND_TYPE <", value, "extendType");
			return (Criteria) this;
		}

		public Criteria andExtendTypeLessThanOrEqualTo(Byte value) {
			addCriterion("EXTEND_TYPE <=", value, "extendType");
			return (Criteria) this;
		}

		public Criteria andExtendTypeIn(List<Byte> values) {
			addCriterion("EXTEND_TYPE in", values, "extendType");
			return (Criteria) this;
		}

		public Criteria andExtendTypeNotIn(List<Byte> values) {
			addCriterion("EXTEND_TYPE not in", values, "extendType");
			return (Criteria) this;
		}

		public Criteria andExtendTypeBetween(Byte value1, Byte value2) {
			addCriterion("EXTEND_TYPE between", value1, value2, "extendType");
			return (Criteria) this;
		}

		public Criteria andExtendTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("EXTEND_TYPE not between", value1, value2,
					"extendType");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeIsNull() {
			addCriterion("FINANCIAL_INCOME is null");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeIsNotNull() {
			addCriterion("FINANCIAL_INCOME is not null");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_INCOME =", value, "financialIncome");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeNotEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_INCOME <>", value, "financialIncome");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeGreaterThan(BigDecimal value) {
			addCriterion("FINANCIAL_INCOME >", value, "financialIncome");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_INCOME >=", value, "financialIncome");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeLessThan(BigDecimal value) {
			addCriterion("FINANCIAL_INCOME <", value, "financialIncome");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_INCOME <=", value, "financialIncome");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeIn(List<BigDecimal> values) {
			addCriterion("FINANCIAL_INCOME in", values, "financialIncome");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeNotIn(List<BigDecimal> values) {
			addCriterion("FINANCIAL_INCOME not in", values, "financialIncome");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FINANCIAL_INCOME between", value1, value2,
					"financialIncome");
			return (Criteria) this;
		}

		public Criteria andFinancialIncomeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FINANCIAL_INCOME not between", value1, value2,
					"financialIncome");
			return (Criteria) this;
		}

		public Criteria andChannelIdIsNull() {
			addCriterion("CHANNEL_ID is null");
			return (Criteria) this;
		}

		public Criteria andChannelIdIsNotNull() {
			addCriterion("CHANNEL_ID is not null");
			return (Criteria) this;
		}

		public Criteria andChannelIdEqualTo(Integer value) {
			addCriterion("CHANNEL_ID =", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotEqualTo(Integer value) {
			addCriterion("CHANNEL_ID <>", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdGreaterThan(Integer value) {
			addCriterion("CHANNEL_ID >", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("CHANNEL_ID >=", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdLessThan(Integer value) {
			addCriterion("CHANNEL_ID <", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdLessThanOrEqualTo(Integer value) {
			addCriterion("CHANNEL_ID <=", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdIn(List<Integer> values) {
			addCriterion("CHANNEL_ID in", values, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotIn(List<Integer> values) {
			addCriterion("CHANNEL_ID not in", values, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdBetween(Integer value1, Integer value2) {
			addCriterion("CHANNEL_ID between", value1, value2, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotBetween(Integer value1, Integer value2) {
			addCriterion("CHANNEL_ID not between", value1, value2, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelNameIsNull() {
			addCriterion("CHANNEL_NAME is null");
			return (Criteria) this;
		}

		public Criteria andChannelNameIsNotNull() {
			addCriterion("CHANNEL_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andChannelNameEqualTo(String value) {
			addCriterion("CHANNEL_NAME =", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotEqualTo(String value) {
			addCriterion("CHANNEL_NAME <>", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameGreaterThan(String value) {
			addCriterion("CHANNEL_NAME >", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
			addCriterion("CHANNEL_NAME >=", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameLessThan(String value) {
			addCriterion("CHANNEL_NAME <", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameLessThanOrEqualTo(String value) {
			addCriterion("CHANNEL_NAME <=", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameLike(String value) {
			addCriterion("CHANNEL_NAME like", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotLike(String value) {
			addCriterion("CHANNEL_NAME not like", value, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameIn(List<String> values) {
			addCriterion("CHANNEL_NAME in", values, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotIn(List<String> values) {
			addCriterion("CHANNEL_NAME not in", values, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameBetween(String value1, String value2) {
			addCriterion("CHANNEL_NAME between", value1, value2, "channelName");
			return (Criteria) this;
		}

		public Criteria andChannelNameNotBetween(String value1, String value2) {
			addCriterion("CHANNEL_NAME not between", value1, value2,
					"channelName");
			return (Criteria) this;
		}

		public Criteria andFinancialCostIsNull() {
			addCriterion("FINANCIAL_COST is null");
			return (Criteria) this;
		}

		public Criteria andFinancialCostIsNotNull() {
			addCriterion("FINANCIAL_COST is not null");
			return (Criteria) this;
		}

		public Criteria andFinancialCostEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_COST =", value, "financialCost");
			return (Criteria) this;
		}

		public Criteria andFinancialCostNotEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_COST <>", value, "financialCost");
			return (Criteria) this;
		}

		public Criteria andFinancialCostGreaterThan(BigDecimal value) {
			addCriterion("FINANCIAL_COST >", value, "financialCost");
			return (Criteria) this;
		}

		public Criteria andFinancialCostGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_COST >=", value, "financialCost");
			return (Criteria) this;
		}

		public Criteria andFinancialCostLessThan(BigDecimal value) {
			addCriterion("FINANCIAL_COST <", value, "financialCost");
			return (Criteria) this;
		}

		public Criteria andFinancialCostLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FINANCIAL_COST <=", value, "financialCost");
			return (Criteria) this;
		}

		public Criteria andFinancialCostIn(List<BigDecimal> values) {
			addCriterion("FINANCIAL_COST in", values, "financialCost");
			return (Criteria) this;
		}

		public Criteria andFinancialCostNotIn(List<BigDecimal> values) {
			addCriterion("FINANCIAL_COST not in", values, "financialCost");
			return (Criteria) this;
		}

		public Criteria andFinancialCostBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FINANCIAL_COST between", value1, value2,
					"financialCost");
			return (Criteria) this;
		}

		public Criteria andFinancialCostNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FINANCIAL_COST not between", value1, value2,
					"financialCost");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxIsNull() {
			addCriterion("MONEY_TAX is null");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxIsNotNull() {
			addCriterion("MONEY_TAX is not null");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxEqualTo(BigDecimal value) {
			addCriterion("MONEY_TAX =", value, "moneyTax");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxNotEqualTo(BigDecimal value) {
			addCriterion("MONEY_TAX <>", value, "moneyTax");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxGreaterThan(BigDecimal value) {
			addCriterion("MONEY_TAX >", value, "moneyTax");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("MONEY_TAX >=", value, "moneyTax");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxLessThan(BigDecimal value) {
			addCriterion("MONEY_TAX <", value, "moneyTax");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxLessThanOrEqualTo(BigDecimal value) {
			addCriterion("MONEY_TAX <=", value, "moneyTax");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxIn(List<BigDecimal> values) {
			addCriterion("MONEY_TAX in", values, "moneyTax");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxNotIn(List<BigDecimal> values) {
			addCriterion("MONEY_TAX not in", values, "moneyTax");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("MONEY_TAX between", value1, value2, "moneyTax");
			return (Criteria) this;
		}

		public Criteria andMoneyTaxNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("MONEY_TAX not between", value1, value2, "moneyTax");
			return (Criteria) this;
		}

		public Criteria andProfitIsNull() {
			addCriterion("PROFIT is null");
			return (Criteria) this;
		}

		public Criteria andProfitIsNotNull() {
			addCriterion("PROFIT is not null");
			return (Criteria) this;
		}

		public Criteria andProfitEqualTo(BigDecimal value) {
			addCriterion("PROFIT =", value, "profit");
			return (Criteria) this;
		}

		public Criteria andProfitNotEqualTo(BigDecimal value) {
			addCriterion("PROFIT <>", value, "profit");
			return (Criteria) this;
		}

		public Criteria andProfitGreaterThan(BigDecimal value) {
			addCriterion("PROFIT >", value, "profit");
			return (Criteria) this;
		}

		public Criteria andProfitGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PROFIT >=", value, "profit");
			return (Criteria) this;
		}

		public Criteria andProfitLessThan(BigDecimal value) {
			addCriterion("PROFIT <", value, "profit");
			return (Criteria) this;
		}

		public Criteria andProfitLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PROFIT <=", value, "profit");
			return (Criteria) this;
		}

		public Criteria andProfitIn(List<BigDecimal> values) {
			addCriterion("PROFIT in", values, "profit");
			return (Criteria) this;
		}

		public Criteria andProfitNotIn(List<BigDecimal> values) {
			addCriterion("PROFIT not in", values, "profit");
			return (Criteria) this;
		}

		public Criteria andProfitBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PROFIT between", value1, value2, "profit");
			return (Criteria) this;
		}

		public Criteria andProfitNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PROFIT not between", value1, value2, "profit");
			return (Criteria) this;
		}

		public Criteria andProfitMarginIsNull() {
			addCriterion("PROFIT_MARGIN is null");
			return (Criteria) this;
		}

		public Criteria andProfitMarginIsNotNull() {
			addCriterion("PROFIT_MARGIN is not null");
			return (Criteria) this;
		}

		public Criteria andProfitMarginEqualTo(BigDecimal value) {
			addCriterion("PROFIT_MARGIN =", value, "profitMargin");
			return (Criteria) this;
		}

		public Criteria andProfitMarginNotEqualTo(BigDecimal value) {
			addCriterion("PROFIT_MARGIN <>", value, "profitMargin");
			return (Criteria) this;
		}

		public Criteria andProfitMarginGreaterThan(BigDecimal value) {
			addCriterion("PROFIT_MARGIN >", value, "profitMargin");
			return (Criteria) this;
		}

		public Criteria andProfitMarginGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PROFIT_MARGIN >=", value, "profitMargin");
			return (Criteria) this;
		}

		public Criteria andProfitMarginLessThan(BigDecimal value) {
			addCriterion("PROFIT_MARGIN <", value, "profitMargin");
			return (Criteria) this;
		}

		public Criteria andProfitMarginLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PROFIT_MARGIN <=", value, "profitMargin");
			return (Criteria) this;
		}

		public Criteria andProfitMarginIn(List<BigDecimal> values) {
			addCriterion("PROFIT_MARGIN in", values, "profitMargin");
			return (Criteria) this;
		}

		public Criteria andProfitMarginNotIn(List<BigDecimal> values) {
			addCriterion("PROFIT_MARGIN not in", values, "profitMargin");
			return (Criteria) this;
		}

		public Criteria andProfitMarginBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("PROFIT_MARGIN between", value1, value2,
					"profitMargin");
			return (Criteria) this;
		}

		public Criteria andProfitMarginNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("PROFIT_MARGIN not between", value1, value2,
					"profitMargin");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeIsNull() {
			addCriterion("BUSINESS_TIME is null");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeIsNotNull() {
			addCriterion("BUSINESS_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeEqualTo(String value) {
			addCriterion("BUSINESS_TIME =", value, "businessTime");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeNotEqualTo(String value) {
			addCriterion("BUSINESS_TIME <>", value, "businessTime");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeGreaterThan(String value) {
			addCriterion("BUSINESS_TIME >", value, "businessTime");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeGreaterThanOrEqualTo(String value) {
			addCriterion("BUSINESS_TIME >=", value, "businessTime");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeLessThan(String value) {
			addCriterion("BUSINESS_TIME <", value, "businessTime");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeLessThanOrEqualTo(String value) {
			addCriterion("BUSINESS_TIME <=", value, "businessTime");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeLike(String value) {
			addCriterion("BUSINESS_TIME like", value, "businessTime");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeNotLike(String value) {
			addCriterion("BUSINESS_TIME not like", value, "businessTime");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeIn(List<String> values) {
			addCriterion("BUSINESS_TIME in", values, "businessTime");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeNotIn(List<String> values) {
			addCriterion("BUSINESS_TIME not in", values, "businessTime");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeBetween(String value1, String value2) {
			addCriterion("BUSINESS_TIME between", value1, value2,
					"businessTime");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeNotBetween(String value1, String value2) {
			addCriterion("BUSINESS_TIME not between", value1, value2,
					"businessTime");
			return (Criteria) this;
		}

		public Criteria andOrderNameLikeInsensitive(String value) {
			addCriterion("upper(ORDER_NAME) like", value.toUpperCase(),
					"orderName");
			return (Criteria) this;
		}

		public Criteria andProductNameLikeInsensitive(String value) {
			addCriterion("upper(PRODUCT_NAME) like", value.toUpperCase(),
					"productName");
			return (Criteria) this;
		}

		public Criteria andCooperateNameLikeInsensitive(String value) {
			addCriterion("upper(COOPERATE_NAME) like", value.toUpperCase(),
					"cooperateName");
			return (Criteria) this;
		}

		public Criteria andChannelNameLikeInsensitive(String value) {
			addCriterion("upper(CHANNEL_NAME) like", value.toUpperCase(),
					"channelName");
			return (Criteria) this;
		}

		public Criteria andBusinessTimeLikeInsensitive(String value) {
			addCriterion("upper(BUSINESS_TIME) like", value.toUpperCase(),
					"businessTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fos_income_cost
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}