package com.imopan.adv.platform.mapper.fos;

import com.imopan.adv.platform.entity.fos.FosAuditChannelDay;
import com.imopan.adv.platform.entity.fos.FosAuditChannelDayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FosAuditChannelDayMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	int countByExample(FosAuditChannelDayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	int insert(FosAuditChannelDay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	int insertSelective(FosAuditChannelDay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	List<FosAuditChannelDay> selectByExample(FosAuditChannelDayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	FosAuditChannelDay selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") FosAuditChannelDay record,
			@Param("example") FosAuditChannelDayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") FosAuditChannelDay record,
			@Param("example") FosAuditChannelDayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(FosAuditChannelDay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_channel_day
	 * @mbggenerated
	 */
	int updateByPrimaryKey(FosAuditChannelDay record);


	void saveBatch(List<FosAuditChannelDay> auditChannelDayList);
}