package com.imopan.adv.platform.mapper.fos;

import com.imopan.adv.platform.entity.fos.FosAuditOrderMonth;
import com.imopan.adv.platform.entity.fos.FosAuditOrderMonthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FosAuditOrderMonthMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	int countByExample(FosAuditOrderMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	int insert(FosAuditOrderMonth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	int insertSelective(FosAuditOrderMonth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	List<FosAuditOrderMonth> selectByExample(FosAuditOrderMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	FosAuditOrderMonth selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") FosAuditOrderMonth record,
			@Param("example") FosAuditOrderMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") FosAuditOrderMonth record,
			@Param("example") FosAuditOrderMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(FosAuditOrderMonth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_audit_order_month
	 * @mbggenerated
	 */
	int updateByPrimaryKey(FosAuditOrderMonth record);
}