package com.imopan.adv.platform.mapper.fos;

import com.imopan.adv.platform.entity.fos.FosChannelMonth;
import com.imopan.adv.platform.entity.fos.FosChannelMonthExample;
import com.imopan.adv.platform.vo.fos.FosAuditChannelMonthVo;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FosChannelMonthMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	int countByExample(FosChannelMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	int insert(FosChannelMonth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	int insertSelective(FosChannelMonth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	List<FosChannelMonth> selectByExample(FosChannelMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	FosChannelMonth selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") FosChannelMonth record,
			@Param("example") FosChannelMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") FosChannelMonth record, @Param("example") FosChannelMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(FosChannelMonth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_channel_month
	 * @mbggenerated
	 */
	int updateByPrimaryKey(FosChannelMonth record);

	/**
     * 
     * findChannelMonth:查询渠道对账数据. <br/> 
     * 
     * @author zhangjiakun
     * @param hashMap
     * @return 
     * @since JDK 1.7
     */
	List<FosChannelMonth> findChannelMonth(HashMap<String, Object> hashMap);

	/**
	 * 
	 * countFindChannelMonth:查询渠道对账数据总数. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	int countFindChannelMonth(HashMap<String, Object> hashMap);

	/**
	 * 
	 * findChannelMonthForReceive:查询渠道对账用于收票操作 <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	List<FosChannelMonth> findChannelMonthForReceive(HashMap<String, Object> hashMap);

	/**
	 * 
	 * countFindChannelMonthForReceive::查询渠道对账总数用于收票操作. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	int countFindChannelMonthForReceive(HashMap<String, Object> hashMap);

	/**
	 * 
	 * insertSelectiveGetId：插入并返回主键. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param fos
	 * @return 
	 * @since JDK 1.7
	 */
	int insertSelectiveGetId(FosChannelMonth fos);

	/**
	 * @param map
	 * @return
	 */
	List<FosAuditChannelMonthVo> getChannelMonthHistoryList(HashMap<String, Object> map);

	/**
	 * @param map
	 * @return
	 */
	int getChannelMonthHistoryList_count(HashMap<String, Object> map);
}