package com.imopan.adv.platform.mapper.fos;

import com.imopan.adv.platform.entity.fos.FosIncomeCost;
import com.imopan.adv.platform.entity.fos.FosIncomeCostExample;
import com.imopan.adv.platform.vo.fos.FosAuditOcDayVo;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FosIncomeCostMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	int countByExample(FosIncomeCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	int insert(FosIncomeCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	int insertSelective(FosIncomeCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	List<FosIncomeCost> selectByExample(FosIncomeCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	FosIncomeCost selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") FosIncomeCost record,
			@Param("example") FosIncomeCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") FosIncomeCost record,
			@Param("example") FosIncomeCostExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fos_income_cost
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FosIncomeCost record);
    
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_income_cost
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(FosIncomeCost record);
    
	List<FosAuditOcDayVo> getIncomeCostHistoryList(HashMap<String, Object> hashMap);
	
	int countGetIncomeCostHistoryList(HashMap<String, Object> hashMap);
	
	List<FosAuditOcDayVo> getIncomeCostHistorySum(HashMap<String, Object> hashMap);

	int countByChannelOrderId(HashMap<String, Object> hashMap);
}