package com.imopan.adv.platform.mapper.fos;

import com.imopan.adv.platform.entity.fos.FosOrder;
import com.imopan.adv.platform.entity.fos.FosOrderExample;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface FosOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order
	 * @mbggenerated
	 */
	int countByExample(FosOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order
	 * @mbggenerated
	 */
	int insert(FosOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order
	 * @mbggenerated
	 */
	int insertSelective(FosOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order
	 * @mbggenerated
	 */
	List<FosOrder> selectByExample(FosOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order
	 * @mbggenerated
	 */
	FosOrder selectByPrimaryKey(Integer orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") FosOrder record,
			@Param("example") FosOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") FosOrder record,
			@Param("example") FosOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(FosOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order
	 * @mbggenerated
	 */
	int updateByPrimaryKey(FosOrder record);

	List<FosOrder> selectByExampleDataController(HashMap<String,Object> hashMap);

	int countByExampleDataController(HashMap<String,Object> hashMap);

}