package com.imopan.adv.platform.mapper.fos;

import com.imopan.adv.platform.entity.fos.FosDailyBill;
import com.imopan.adv.platform.entity.fos.FosOcDay;
import com.imopan.adv.platform.entity.fos.FosOcDayExample;
import com.imopan.adv.platform.vo.fos.FosAuditOcDayVo;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface FosOcDayMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_oc_day
	 * @mbggenerated
	 */
	int countByExample(FosOcDayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_oc_day
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_oc_day
	 * @mbggenerated
	 */
	int insert(FosOcDay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_oc_day
	 * @mbggenerated
	 */
	int insertSelective(FosOcDay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_oc_day
	 * @mbggenerated
	 */
	List<FosOcDay> selectByExample(FosOcDayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_oc_day
	 * @mbggenerated
	 */
	FosOcDay selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_oc_day
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") FosOcDay record,
			@Param("example") FosOcDayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_oc_day
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") FosOcDay record,
			@Param("example") FosOcDayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_oc_day
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(FosOcDay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_oc_day
	 * @mbggenerated
	 */
	int updateByPrimaryKey(FosOcDay record);

	/**
     * 
     * saveBatch:批量保存. <br/> 
     * 
     * @author zhangjiakun 
     * @param arrayList 
     * @since JDK 1.7
     */
	void saveBatch(List<FosOcDay> arrayList);

	/**
	 * 
	 * updateBatch:批量更新. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param fos 
	 * @since JDK 1.7
	 */
	void updateBatch(List<FosOcDay> fos);

	/**
	 * 
	 * getDayBillList:日账单查询. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	List<FosDailyBill> getDayBillList(HashMap<String, Object> hashMap);

	/**
	 * 
	 * countGetDayBillList:日账单查询总数. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	int countGetDayBillList(HashMap<String, Object> hashMap);


	List<Map<String, Object>> getChartCooperateName(HashMap<String, Object> hashMap);

	List<Map<String, Object>> getChartChannel(HashMap<String, Object> hashMap);

	List<Map<String, Object>> getChartOrderDirectorName(HashMap<String, Object> hashMap);

	List<Map<String, Object>> getChartChannel_Line(HashMap<String, Object> hashMap);

	List<Map<String, Object>> getChartCooperateName_Line(HashMap<String, Object> hashMap);

	List<Map<String, Object>> getChartOrderDirectorName_Line(HashMap<String, Object> hashMap);

	List<Map<String, Object>> getAllName(HashMap<String, Object> hashMap);

	List<FosOcDay> getOcDayListSum(HashMap<String, Object> hashMap);

	List<FosAuditOcDayVo> getAuditOcDayList(HashMap<String, Object> hashMap);
	
	List<FosAuditOcDayVo> getAuditOcDayInfoSum(HashMap<String, Object> hashMap);

	int countGetAuditOcDayList(HashMap<String, Object> hashMap);
	
	List<FosAuditOcDayVo> getIncomeAndCostList(HashMap<String, Object> hashMap);
	
	int countGetIncomeAndCostList(HashMap<String, Object> hashMap);

	List<FosOcDay> getOcDayList(Map<String, Object> hashMap);

	int countGetOcDayList(Map<String, Object> hashMap);

	void updateChannelMonthStatus(Map<String, Object> map);

	void updateOrderMonthStatus(Map<String, Object> map);
	
}