package com.imopan.adv.platform.mapper.fos;

import com.imopan.adv.platform.entity.fos.FosCycleBill;
import com.imopan.adv.platform.entity.fos.FosOrderMonth;
import com.imopan.adv.platform.entity.fos.FosOrderMonthExample;
import com.imopan.adv.platform.vo.fos.FosAuditOrderMonthVo;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface FosOrderMonthMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order_month
	 * @mbggenerated
	 */
	int countByExample(FosOrderMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order_month
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order_month
	 * @mbggenerated
	 */
	int insert(FosOrderMonth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order_month
	 * @mbggenerated
	 */
	int insertSelective(FosOrderMonth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order_month
	 * @mbggenerated
	 */
	List<FosOrderMonth> selectByExample(FosOrderMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order_month
	 * @mbggenerated
	 */
	FosOrderMonth selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order_month
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") FosOrderMonth record, @Param("example") FosOrderMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order_month
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") FosOrderMonth record, @Param("example") FosOrderMonthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order_month
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(FosOrderMonth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_order_month
	 * @mbggenerated
	 */
	int updateByPrimaryKey(FosOrderMonth record);

	/**
	 * 
	 * findOrderMonth:查询订单对账数据. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	List<FosOrderMonth> findOrderMonth(HashMap<String, Object> hashMap);

	/**
	 * 
	 * countFindOrderMonth:查询订单对账数据总条数. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	int countFindOrderMonth(HashMap<String, Object> hashMap);

	/**
	 * 
	 * findCycleBillList:周期账单. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	List<FosCycleBill> findCycleBillList(HashMap<String, Object> hashMap);

	/**
	 * 
	 * countFindCycleBillList:周期账单总数. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	int countFindCycleBillList(HashMap<String, Object> hashMap);

	/**
	 * 
	 * findCycleBillListSum:周期账单求和. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	List<FosCycleBill> findCycleBillListSum(HashMap<String, Object> hashMap);

	/**
	 * 
	 * findCycleBillDetail:周期订单详情. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	List<FosCycleBill> findCycleBillDetail(HashMap<String, Object> hashMap);

	/**
	 * 
	 * countFindCycleBillDetail:周期订单详情条数. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	int countFindCycleBillDetail(HashMap<String, Object> hashMap);

	/**
	 * 
	 * findCycleBillDetailSum:周期订单详情合计. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	FosCycleBill findCycleBillDetailSum(HashMap<String, Object> hashMap);

	/**
	 * 
	 * insertSelectiveGetId:插入并返回id. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param fos
	 * @return 
	 * @since JDK 1.7
	 */
	int insertSelectiveGetId(FosOrderMonth fos);

	
	/**
	 * 
	 * getAuditOrderMonthList:订单对账审核列表. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	List<FosAuditOrderMonthVo> getAuditOrderMonthList(
			HashMap<String, Object> hashMap);

	int countGetAuditOrderMonthList(HashMap<String, Object> hashMap);
}