package com.imopan.adv.platform.mapper.fos;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.imopan.adv.platform.entity.fos.FosOrderChannel;
import com.imopan.adv.platform.entity.fos.FosOrderChannelExample;

public interface FosOrderChannelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fos_order_channel
	 * 
	 * @mbggenerated
	 */
	int countByExample(FosOrderChannelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fos_order_channel
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer channelOrderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fos_order_channel
	 * 
	 * @mbggenerated
	 */
	int insert(FosOrderChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fos_order_channel
	 * 
	 * @mbggenerated
	 */
	int insertSelective(FosOrderChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fos_order_channel
	 * 
	 * @mbggenerated
	 */
	List<FosOrderChannel> selectByExample(FosOrderChannelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fos_order_channel
	 * 
	 * @mbggenerated
	 */
	FosOrderChannel selectByPrimaryKey(Integer channelOrderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fos_order_channel
	 * 
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") FosOrderChannel record,
			@Param("example") FosOrderChannelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fos_order_channel
	 * 
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") FosOrderChannel record, @Param("example") FosOrderChannelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fos_order_channel
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(FosOrderChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fos_order_channel
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(FosOrderChannel record);

	/**
	 * 
	 * saveBatch:批量保存. <br/>
	 * 
	 * @author zhangjiakun
	 * @param list
	 * @since JDK 1.7
	 */
	void saveBatch(List<FosOrderChannel> list);

	/**
	 * 
	 * countFindByExample:查询渠道订单总数. <br/>
	 * 
	 * @author zhangjiakun
	 * @param map
	 * @return
	 * @since JDK 1.7
	 */
	int countFindByExample(HashMap<String, Object> map);
}