package com.imopan.adv.platform.mapper.fos;

import com.imopan.adv.platform.entity.fos.FosSystemLog;
import com.imopan.adv.platform.entity.fos.FosSystemLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FosSystemLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	int countByExample(FosSystemLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	int insert(FosSystemLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	int insertSelective(FosSystemLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	List<FosSystemLog> selectByExampleWithBLOBs(FosSystemLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	List<FosSystemLog> selectByExample(FosSystemLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	FosSystemLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") FosSystemLog record, @Param("example") FosSystemLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") FosSystemLog record, @Param("example") FosSystemLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") FosSystemLog record, @Param("example") FosSystemLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(FosSystemLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(FosSystemLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_system_log
	 * @mbggenerated
	 */
	int updateByPrimaryKey(FosSystemLog record);
}