package com.imopan.adv.platform.mapper.fos;

import com.imopan.adv.platform.entity.fos.FosTicketOrder;
import com.imopan.adv.platform.entity.fos.FosTicketOrderExample;
import com.imopan.adv.platform.entity.fos.FosTicketOrderImpl;
import com.imopan.adv.platform.vo.fos.FosTicketOrderVo;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface FosTicketOrderMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_ticket_order
	 * @mbggenerated
	 */
	int countByExample(FosTicketOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_ticket_order
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_ticket_order
	 * @mbggenerated
	 */
	int insert(FosTicketOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_ticket_order
	 * @mbggenerated
	 */
	int insertSelective(FosTicketOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_ticket_order
	 * @mbggenerated
	 */
	List<FosTicketOrder> selectByExample(FosTicketOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_ticket_order
	 * @mbggenerated
	 */
	FosTicketOrder selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_ticket_order
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") FosTicketOrder record,
			@Param("example") FosTicketOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_ticket_order
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") FosTicketOrder record,
			@Param("example") FosTicketOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_ticket_order
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(FosTicketOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fos_ticket_order
	 * @mbggenerated
	 */
	int updateByPrimaryKey(FosTicketOrder record);

	/**
     * 
     * findTicketOrder:获得出票列表. <br/> 
     * 
     * @author zhangjiakun
     * @param hashMap
     * @return 
     * @since JDK 1.7
     */
	List<FosTicketOrder> findTicketOrder(HashMap<String, Object> hashMap);

	/**
	 * 
	 * countFindTicketOrder:获取出票列表数量. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	int countFindTicketOrder(HashMap<String, Object> hashMap);

	
	/**
	 * 
	 * findReceiptHistoryList:获取回款的所有列表. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	List<FosTicketOrderVo> findReceiptHistoryList(HashMap<String, Object> hashMap);

	/**
	 * 
	 * countFindReceiptHistoryList:获取回款的所有列表总数. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	int countFindReceiptHistoryList(HashMap<String, Object> hashMap);

	/**
	 * 
	 * findReceiptHistoryListSum:获取回款列表的合计. <br/> 
	 * 
	 * @author zhangjiakun
	 * @param hashMap
	 * @return 
	 * @since JDK 1.7
	 */
	List<FosTicketOrderVo> findReceiptHistoryListSum(HashMap<String, Object> hashMap);

	List<FosTicketOrder> findAdutiTicketOrder(HashMap<String, Object> hashMap);

	int countFindAdutiTicketOrder(HashMap<String, Object> hashMap);
	/**
	 * 获取所有的开票信息
	 * @param ex
	 * @return
	 */
	List<FosTicketOrderImpl> getMonthIncomeHistoryList(Map<String,Object> map);

	/**
	 * 统计所有的开票信息的金额
	 * @param map
	 * @return
	 */
	int countMonthIncomeByExample(Map<String, Object> map);
	
	List<FosTicketOrder> getDrawHistoryList(Map<String, Object> hashMap);

	int countGetDrawHistoryList(Map<String, Object> hashMap);
	/**
	 * 统计符合条件内的开票金额
	 * @param map
	 * @return
	 */
	List<FosTicketOrderImpl> getMonthIncomeSum(Map<String, Object> map);
}